/**
 * Automatic content generation task handler
 * This file contains the scheduled job logic for automatically generating and publishing content
 * based on user configurations. It's designed to run periodically.
 */

// Implementation ready for when the schema is created

import { db } from './db';
import { eq, and, gte, lt, sql, desc } from 'drizzle-orm';
import { 
  users,
  autoContentConfigs,
  autoGeneratedContents,
  contentTypeEnum
} from '@shared/schema';
import { storage } from './storage';
import * as openai from './openai';
import { createAnimation, AnimationOptions } from './animatediff-service';

// Placeholder to prevent errors
const PLATFORMS = ['linkedin', 'facebook', 'instagram', 'twitter', 'gmb', 'pinterest'];
const ARTICLE_WORD_COUNTS = {
  'article-short': 600,
  'article-medium': 1000,
  'article-long': 2000
};

/**
 * Process automatic content generation for all eligible users
 * This function finds all users with active Inferno subscriptions and valid auto-content configs,
 * then creates scheduled content for them based on their frequency settings
 */
export async function processAutoContentGeneration() {
  console.log('Running automatic content generation task...');
  const now = new Date();
  
  try {
    // Get all users with Inferno plan that have auto content config set up
    const activeUsers = await db.select()
      .from(users)
      .innerJoin(autoContentConfigs, eq(users.id, autoContentConfigs.userId))
      .where(eq(users.plan, 'inferno'));
    
    console.log(`Found ${activeUsers.length} active users with auto content configured`);
    
    for (const { users: user, auto_content_configs: config } of activeUsers) {
      // Skip if not enabled
      if (!config.enabled) {
        console.log(`Skipping user ${user.id}: auto content not enabled`);
        continue;
      }
      
      // Check if we need to generate content based on frequency
      // Calculate next publish date based on last generated content or config created date
      
      // Get the most recent auto-generated content for this user
      const [lastContent] = await db.select()
        .from(autoGeneratedContents)
        .where(eq(autoGeneratedContents.userId, user.id))
        .orderBy(desc(autoGeneratedContents.createdAt))
        .limit(1);
      
      let baseDate = lastContent ? lastContent.createdAt : config.createdAt;
      let nextScheduleDate: Date;
      
      switch (config.postFrequency) {
        case 'daily':
          // Add 1 day
          nextScheduleDate = new Date(baseDate);
          nextScheduleDate.setDate(nextScheduleDate.getDate() + 1);
          break;
        
        case 'weekly': 
          // Add 7 days
          nextScheduleDate = new Date(baseDate);
          nextScheduleDate.setDate(nextScheduleDate.getDate() + 7);
          break;
          
        case 'bi-weekly':
          // Add 14 days
          nextScheduleDate = new Date(baseDate);
          nextScheduleDate.setDate(nextScheduleDate.getDate() + 14);
          break;
          
        case 'monthly':
          // Add 1 month
          nextScheduleDate = new Date(baseDate);
          nextScheduleDate.setMonth(nextScheduleDate.getMonth() + 1);
          break;
          
        default:
          console.log(`Skipping user ${user.id}: invalid frequency ${config.postFrequency}`);
          continue;
      }
      
      // Check if we've reached the next schedule date
      if (nextScheduleDate > now) {
        console.log(`Skipping user ${user.id}: next schedule date ${nextScheduleDate.toISOString()} is in the future`);
        continue;
      }
      
      console.log(`Generating content for user ${user.id} with schedule date ${nextScheduleDate.toISOString()}`);
      
      // Check if user already has pending content scheduled
      const pendingContent = await db.select()
        .from(autoGeneratedContents)
        .where(
          and(
            eq(autoGeneratedContents.userId, user.id),
            eq(autoGeneratedContents.status, 'pending')
          )
        );
      
      if (pendingContent.length > 0) {
        console.log(`Skipping user ${user.id}: already has ${pendingContent.length} pending items`);
        continue;
      }
      
      // Generate content for this user
      try {
        // Get company profile if exists
        const companyProfile = await storage.getCompanyProfile(user.id);
        
        // Create content prompt
        const contentType = config.includeImages ? 'both' : 'text';
        let prompt = `Generate ${contentType} content`;
        
        if (config.topicCategories && config.topicCategories.length > 0) {
          prompt += ` about ${config.topicCategories.join(', ')}`;
        }
        
        if (config.contentTone) {
          prompt += ` in a ${config.contentTone} tone`;
        }
        
        // Add company context if available
        if (companyProfile) {
          prompt += `. This is for a company called ${companyProfile.companyName}`;
          
          if (companyProfile.industry) {
            prompt += ` in the ${companyProfile.industry} industry`;
          }
          
          if (companyProfile.description) {
            prompt += `. ${companyProfile.description}`;
          }
        }
        
        prompt += `. Create content suitable for these platforms: ${config.platforms.join(', ') || PLATFORMS.join(', ')}.`;
        
        if (config.customNotes) {
          prompt += ` ${config.customNotes}`;
        }
        
        // Determine content type and length requirements
        const contentSettings = config.contentTypes && config.contentTypes[0];
        let length = 'medium';
        let wordCount = 1000;
        let includeHashtags = false;
        
        // Set word count based on content type
        if (contentSettings && contentSettings.startsWith('article-')) {
          // Get word count for article type
          wordCount = ARTICLE_WORD_COUNTS[contentSettings] || 1000;
          
          // Update prompt with specific word count
          prompt += `. Content should be approximately ${wordCount} words in length.`;
          
          // Set length parameter
          if (wordCount <= 600) length = 'short';
          else if (wordCount <= 1000) length = 'medium';
          else length = 'long';
        } else if (contentSettings === 'social') {
          // Social media post
          length = 'short';
          includeHashtags = true;
          prompt += `. For social posts, include exactly 3 hashtags at the end that are relevant to the content and industry.`;
          
          // Add platform-specific requirements
          if (platform === 'twitter') {
            prompt += ` Keep Twitter posts under 280 characters including hashtags.`;
          } else if (platform === 'instagram') {
            prompt += ` Instagram captions should be engaging and include line breaks for readability.`;
          } else if (platform === 'linkedin') {
            prompt += ` LinkedIn posts should be professional with a call to action.`;
          }
        }
        
        // Add company branding requirement
        prompt += ` Always incorporate the company's brand voice and messaging.`;
        
        // Generate content
        console.log(`Generating content with prompt: ${prompt}`);
        const content = await openai.generateContent({
          prompt,
          contentType: contentType as 'text' | 'image' | 'both',
          tone: config.contentTone,
          length,
          wordCount,
          includeHashtags
        });
        
        // Schedule the content for the target platforms
        const targetPlatforms = config.platforms.length > 0 ? config.platforms : PLATFORMS;
        
        for (const platform of targetPlatforms) {
          // Schedule for a later time in the day
          const scheduleDate = new Date(nextScheduleDate);
          // Add random hours to spread out publishing (1-8 hours)
          scheduleDate.setHours(scheduleDate.getHours() + Math.floor(Math.random() * 8) + 1);
          
          // Generate a simple title from content
          const titlePrefix = config.topicCategories.length > 0 ? 
            config.topicCategories[0].charAt(0).toUpperCase() + config.topicCategories[0].slice(1) : 
            'Content';
          
          // Check if we should animate the image
          let animatedImageUrl = null;
          if (config.includeImages && config.animateImages && content.imageUrl) {
            try {
              // Create animation from the generated image
              const animationOptions: AnimationOptions = {
                imageUrl: content.imageUrl,
                motionStyle: config.animationStyle || 'default',
                looping: true,
                outputFormat: 'mp4',
                numFrames: 24,
                fps: 8
              };
              
              console.log(`Creating animation for content with options:`, animationOptions);
              const animation = await createAnimation(animationOptions);
              
              // Use the animation URL
              animatedImageUrl = animation.url;
              console.log(`Created animation: ${animatedImageUrl}`);
            } catch (animationError) {
              console.error(`Error creating animation:`, animationError);
              // Continue without animation if there's an error
            }
          }
          
          await storage.createAutoGeneratedContent({
            userId: user.id,
            configId: config.id,
            title: `${titlePrefix} post for ${platform}`,
            textContent: content.text || '',
            imageUrl: animatedImageUrl || content.imageUrl || null,
            contentType: contentType === 'both' ? 'both' : (contentType === 'image' ? 'image' : 'text') as any,
            platform: platform as any, // Type casting to match schema
            scheduledDate: scheduleDate,
            status: 'pending',
            metadata: {
              isAnimated: !!animatedImageUrl,
              animationStyle: config.animationStyle,
              originalImageUrl: animatedImageUrl ? content.imageUrl : null
            }
          });
          
          console.log(`Created scheduled content for user ${user.id} on ${platform} platform for ${scheduleDate.toISOString()}`);
        }
        
        // Update the last content generation timestamp in the config
        // We don't have a lastPublishedDate field, so we'll use the updatedAt timestamp
        await db.update(autoContentConfigs)
          .set({ updatedAt: now })
          .where(eq(autoContentConfigs.id, config.id));
        
        console.log(`Updated lastPublishedDate for user ${user.id}`);
        
      } catch (error) {
        console.error(`Error generating content for user ${user.id}:`, error);
        // Continue with next user
      }
    }
    
    console.log('Completed auto content generation task');
  } catch (error) {
    console.error('Error in auto content generation task:', error);
  }
}

/**
 * Process content publication for all scheduled content that is due
 * This function finds all pending auto-generated content items and publishes them
 * when their scheduled date is reached
 */
export async function processScheduledContentPublication() {
  console.log('Running scheduled content publication task...');
  const now = new Date();
  
  try {
    // Find all pending scheduled content items that need to be published
    const scheduledItems = await db.select()
      .from(autoGeneratedContents)
      .where(
        and(
          eq(autoGeneratedContents.status, 'pending'),
          lt(autoGeneratedContents.scheduledDate, now)
        )
      );
    
    console.log(`Found ${scheduledItems.length} items to publish`);
    
    for (const item of scheduledItems) {
      try {
        // In a real application, this would integrate with the social media APIs
        // For now, we'll just mark it as published
        
        // Check if this is an animated content
        const isAnimated = item.metadata && item.metadata.isAnimated;
        
        // Mark as published
        await storage.markAutoContentPublished(item.id, JSON.stringify({
          platform: item.platform,
          publishedAt: now.toISOString(),
          isAnimated,
          animationStyle: isAnimated ? item.metadata.animationStyle : null,
          // Simulate some engagement metrics
          metrics: {
            views: Math.floor(Math.random() * 1000),
            likes: Math.floor(Math.random() * 100),
            shares: Math.floor(Math.random() * 20),
            comments: Math.floor(Math.random() * 10),
            total: Math.floor(Math.random() * 1130) // combined engagement
          }
        }));
        
        console.log(`Published content item ${item.id} for user ${item.userId} on ${item.platform}${isAnimated ? ' (animated)' : ''}`);
      } catch (error) {
        console.error(`Error publishing content item ${item.id}:`, error);
        // Continue with next item
      }
    }
    
    console.log('Completed scheduled content publication task');
  } catch (error) {
    console.error('Error in scheduled content publication task:', error);
  }
}

/**
 * Initialize periodic tasks
 * @param intervalMinutes - How often to run the tasks (in minutes)
 */
export function initAutoContentTasks(intervalMinutes = 15) {
  const interval = intervalMinutes * 60 * 1000; // Convert to milliseconds
  
  // Run content generation task
  setInterval(processAutoContentGeneration, interval);
  console.log(`Auto content generation task scheduled to run every ${intervalMinutes} minutes`);
  
  // Run content publication task
  setInterval(processScheduledContentPublication, interval / 3); // Run publication more frequently
  console.log(`Content publication task scheduled to run every ${intervalMinutes / 3} minutes`);
  
  // Run tasks immediately upon startup
  setTimeout(() => {
    processAutoContentGeneration();
    processScheduledContentPublication();
  }, 10000); // Delay first run by 10 seconds to let the server start up
}