import type { Express, Request, Response, NextFunction } from "express";
import { createServer, type Server } from "http";
import Stripe from "stripe";
import { db } from "./db";
import { setupAuth } from "./auth";
import { contentPipelineService } from "./cds-integration";
import {
  users,
  contents,
  schedules,
  contentTypeEnum,
  contentStatusEnum,
  frequencyEnum,
  toneEnum,
  platformEnum,
  companyProfiles,
  autoContentConfigs,
  autoGeneratedContents,
  autoContentStatusEnum,
  adminSettings,
  businessHours,
  businessListings,
  listingPlatformEnum,
  listingSyncStatusEnum,
  listingSyncTasks,
  taskStatusEnum,
  businessReviews,
  huginnAgents,
  huginnWorkflows,
  huginnLogs,
  agentTypeEnum,
  contentPipelines,
  contentPipelineRuns,
  contentPipelineStages,
  contentPipelineJobs,
  pipelineRunStatusEnum,
  agentStatusEnum,
  agentScheduleEnum,
  agentTriggerEnum
} from "@shared/schema";
import { eq, and, or, gte, lte, desc, asc, sql, not, isNull, inArray } from "drizzle-orm";
import { factCheck, type FactCheckRequest, getReferences, type ReferencesRequest } from "./perplexity";
import OpenAI from "openai";
import { generateContent, type ContentPrompt, type GeneratedContent, getRelevantSources } from "./openai";
import { enhanceContent } from "./anthropic";
import { repurposeContent, type RepurposeRequest, type RepurposeResponse } from "./content-repurpose";
// Auto content tasks temporarily disabled until schema components are implemented
// import { initAutoContentTasks } from "./auto-content-task";
import { huginnAgentService } from "./huginn-agents";
import { processAssistantMessage } from "./assistant";

if (!process.env.STRIPE_SECRET_KEY) {
  console.warn("STRIPE_SECRET_KEY is not set. Stripe integration will be disabled.");
}

const stripe = process.env.STRIPE_SECRET_KEY
  ? new Stripe(process.env.STRIPE_SECRET_KEY, {
      apiVersion: "2023-10-16",
    })
  : null;

// Subscription plans
const EMBER_PLAN_PRICE_ID = "price_ember_monthly"; // $99/month
const INFERNO_PLAN_PRICE_ID = "price_inferno_monthly"; // $999/month

export function registerRoutes(app: Express): Server {
  setupAuth(app);

  // Start auto-content tasks (will check for eligible users based on plan type)
  // Temporarily disabled until schema components are implemented
  // initAutoContentTasks();

  // Subscription management endpoints
  
  // Ember Plan - $99/month with 1 post per day, 1 platform 
  app.post('/api/subscribe/ember', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    if (!stripe) {
      return res.status(503).json({ message: 'Stripe integration not available' });
    }
    
    try {
      const user = req.user;
      
      if (user.stripeCustomerId && user.stripeSubscriptionId) {
        return res.status(400).json({ message: 'User already has a subscription' });
      }
      
      // Create or retrieve customer
      let customerId = user.stripeCustomerId;
      
      if (!customerId) {
        const customer = await stripe.customers.create({
          email: user.email || '',
          name: user.username,
          metadata: {
            userId: user.id.toString(),
          }
        });
        
        customerId = customer.id;
        
        // Update user with customer ID
        await db.update(users)
          .set({ stripeCustomerId: customerId })
          .where(eq(users.id, user.id));
      }
      
      // Create subscription for Ember plan ($99/month)
      const subscription = await stripe.subscriptions.create({
        customer: customerId,
        items: [{ price: EMBER_PLAN_PRICE_ID }],
        payment_behavior: 'default_incomplete',
        expand: ['latest_invoice.payment_intent'],
      });
      
      // Update user record with Ember plan
      await db.update(users)
        .set({ 
          stripeSubscriptionId: subscription.id,
          plan: 'ember',
          planStatus: 'active',
        })
        .where(eq(users.id, user.id));
      
      res.json({
        subscriptionId: subscription.id,
        clientSecret: (subscription.latest_invoice as any)?.payment_intent?.client_secret,
      });
    } catch (error: any) {
      console.error('Subscription creation error:', error);
      res.status(500).json({ message: `Error creating subscription: ${error.message}` });
    }
  });
  
  // Inferno Plan - $999/month with all premium features
  app.post('/api/subscribe/inferno', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    if (!stripe) {
      return res.status(503).json({ message: 'Stripe integration not available' });
    }
    
    try {
      const user = req.user;
      
      if (user.stripeCustomerId && user.stripeSubscriptionId) {
        return res.status(400).json({ message: 'User already has a subscription' });
      }
      
      // Create or retrieve customer
      let customerId = user.stripeCustomerId;
      
      if (!customerId) {
        const customer = await stripe.customers.create({
          email: user.email || '',
          name: user.username,
          metadata: {
            userId: user.id.toString(),
          }
        });
        
        customerId = customer.id;
        
        // Update user with customer ID
        await db.update(users)
          .set({ stripeCustomerId: customerId })
          .where(eq(users.id, user.id));
      }
      
      // Create subscription for Inferno plan ($999/month)
      const subscription = await stripe.subscriptions.create({
        customer: customerId,
        items: [{ price: INFERNO_PLAN_PRICE_ID }],
        payment_behavior: 'default_incomplete',
        expand: ['latest_invoice.payment_intent'],
      });
      
      // Update user record with Inferno plan
      await db.update(users)
        .set({ 
          stripeSubscriptionId: subscription.id,
          plan: 'inferno',
          planStatus: 'active',
        })
        .where(eq(users.id, user.id));
      
      res.json({
        subscriptionId: subscription.id,
        clientSecret: (subscription.latest_invoice as any)?.payment_intent?.client_secret,
      });
    } catch (error: any) {
      console.error('Subscription creation error:', error);
      res.status(500).json({ message: `Error creating subscription: ${error.message}` });
    }
  });
  
  app.get('/api/subscription', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    if (!stripe) {
      return res.status(503).json({ message: 'Stripe integration not available' });
    }
    
    try {
      const user = req.user;
      
      if (!user.stripeSubscriptionId) {
        return res.json({
          status: 'no-subscription',
          plan: user.plan || 'free',
          planStatus: user.planStatus || 'inactive',
        });
      }
      
      const subscription = await stripe.subscriptions.retrieve(user.stripeSubscriptionId);
      
      return res.json({
        status: subscription.status,
        currentPeriodEnd: new Date(subscription.current_period_end * 1000),
        cancelAtPeriodEnd: subscription.cancel_at_period_end,
        plan: user.plan,
        planStatus: user.planStatus,
      });
    } catch (error: any) {
      console.error('Error fetching subscription:', error);
      res.status(500).json({ message: `Error fetching subscription: ${error.message}` });
    }
  });
  
  app.post('/api/subscription/cancel', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    if (!stripe) {
      return res.status(503).json({ message: 'Stripe integration not available' });
    }
    
    try {
      const user = req.user;
      
      if (!user.stripeSubscriptionId) {
        return res.status(400).json({ message: 'No active subscription' });
      }
      
      const subscription = await stripe.subscriptions.update(user.stripeSubscriptionId, {
        cancel_at_period_end: true,
      });
      
      // Update user plan status
      await db.update(users)
        .set({ planStatus: 'cancelling' })
        .where(eq(users.id, user.id));
      
      return res.json({
        status: subscription.status,
        cancelAtPeriodEnd: subscription.cancel_at_period_end,
        currentPeriodEnd: new Date(subscription.current_period_end * 1000),
      });
    } catch (error: any) {
      console.error('Error cancelling subscription:', error);
      res.status(500).json({ message: `Error cancelling subscription: ${error.message}` });
    }
  });
  
  app.post('/api/subscription/resume', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    if (!stripe) {
      return res.status(503).json({ message: 'Stripe integration not available' });
    }
    
    try {
      const user = req.user;
      
      if (!user.stripeSubscriptionId) {
        return res.status(400).json({ message: 'No active subscription' });
      }
      
      const subscription = await stripe.subscriptions.update(user.stripeSubscriptionId, {
        cancel_at_period_end: false,
      });
      
      // Update user plan status
      await db.update(users)
        .set({ planStatus: 'active' })
        .where(eq(users.id, user.id));
      
      return res.json({
        status: subscription.status,
        cancelAtPeriodEnd: subscription.cancel_at_period_end,
        currentPeriodEnd: new Date(subscription.current_period_end * 1000),
      });
    } catch (error: any) {
      console.error('Error resuming subscription:', error);
      res.status(500).json({ message: `Error resuming subscription: ${error.message}` });
    }
  });
  
  // Content generation endpoints
  app.post('/api/content/generate', async (req: Request, res: Response) => {
    console.log("==== Content generation request received ====");
    console.log("Auth status:", req.isAuthenticated());
    console.log("User:", req.user ? req.user.id : "none");
    
    if (!req.isAuthenticated()) {
      console.log("Not authenticated, returning 401");
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      console.log("Request body:", JSON.stringify(req.body, null, 2));
      
      const { 
        prompt, 
        contentType, 
        tone, 
        length, 
        personality, 
        platform,
        template,
        templateData
      } = req.body;
      
      console.log("OPENAI_API_KEY exists:", !!process.env.OPENAI_API_KEY);
      console.log("PERPLEXITY_API_KEY exists:", !!process.env.PERPLEXITY_API_KEY);
      console.log("ANTHROPIC_API_KEY exists:", !!process.env.ANTHROPIC_API_KEY);
      
      // Log template and template data for debugging
      console.log("Using template:", template || 'standard');
      if (template !== 'standard' && templateData) {
        console.log("Template data:", JSON.stringify(templateData, null, 2));
      }
      
      console.log("Parsed content values:", { 
        promptLength: prompt ? prompt.length : 0, 
        contentType, 
        tone, 
        length, 
        personality, 
        platform,
        template: template || 'standard',
        hasTemplateData: templateData ? true : false
      });
      
      // Make validation more flexible for debugging
      if (template === 'standard' && !prompt) {
        console.warn('Missing prompt for standard template, but continuing for testing');
      }
      
      if (template && template !== 'standard' && !templateData) {
        console.warn(`Missing template data for ${template}, but continuing for testing`);
      }
      
      // Add plan-based validation and limitations
      const user = req.user;
      console.log("User confirmed:", user.id, user.username);
      
      // Ember plan users are limited to 1 post per day
      if (user.plan === 'ember') {
        // Check if user has already created a post today
        const today = new Date();
        today.setHours(0, 0, 0, 0);
        
        const postsToday = await db.select()
          .from(contents)
          .where(
            and(
              eq(contents.userId, user.id),
              gte(contents.createdAt, today)
            )
          );
          
        if (postsToday.length >= 1) {
          return res.status(403).json({ 
            message: 'Ember plan is limited to 1 post per day. Upgrade to Inferno plan for unlimited posts.'
          });
        }
      }
      
      // Get company profile to personalize content
      let companyContext = "";
      try {
        const [companyProfile] = await db.select()
          .from(companyProfiles)
          .where(eq(companyProfiles.userId, user.id));

        if (companyProfile) {
          // Create a company context to personalize content
          companyContext = `
            Company Name: ${companyProfile.name || ""}
            Industry: ${companyProfile.industry || ""}
            Description: ${companyProfile.description || ""}
            Website: ${companyProfile.website || ""}
          `;
          
          console.log("Using company profile for content generation");
        }
      } catch (err) {
        console.log("No company profile found, proceeding without company context");
      }
      
      console.log("Calling generateContent with prompt length:", prompt ? prompt.length : 0);
      
      const result: GeneratedContent = await generateContent({ 
        prompt: prompt || 'Generate quality content', // Default prompt if none provided
        contentType: contentType || 'text', 
        tone: tone || 'professional', 
        length: length || 'medium', 
        personality: personality || 'thoughtful',
        platform: platform || null,
        template: template || 'standard',
        templateData: templateData || {},
        companyContext
      });
      
      console.log("Content generated successfully");
      return res.json(result);
    } catch (error: any) {
      console.error('Content generation error:', error);
      return res.status(500).json({ message: `Error generating content: ${error.message}` });
    }
  });

  const httpServer = createServer(app);
  return httpServer;
}