import express, { type Express, Request, Response } from "express";
import { createServer, type Server } from "http";
import { storage } from "./storage";
import { setupAuth } from "./auth";
import openai from "./openai";
import Stripe from "stripe";
import { handleWebhook } from "./webhooks";
import { eq, and, sql } from "drizzle-orm";
import { db } from "./db";
import { 
  adminSettings, 
  users, 
  insertCompanyProfileSchema, 
  insertAutoContentConfigSchema,
  insertAutoGeneratedContentSchema,
  insertBusinessHoursSchema,
  insertBusinessListingSchema,
  insertListingSyncTaskSchema,
  insertBusinessReviewSchema,
  autoContentConfigs,
  autoGeneratedContents
} from "@shared/schema";
import { hashPassword } from "./auth";
import { factCheck, getReferences, FactCheckRequest, ReferencesRequest } from "./perplexity";
import { repurposeContent, RepurposeRequest } from "./content-repurpose";

if (!process.env.STRIPE_SECRET_KEY) {
  console.warn('Missing STRIPE_SECRET_KEY - payment features will not work properly');
}

const stripe = process.env.STRIPE_SECRET_KEY ? new Stripe(process.env.STRIPE_SECRET_KEY, {
  apiVersion: "2023-10-16",
}) : undefined;

export async function registerRoutes(app: Express): Promise<Server> {
  // Sets up auth routes: /api/register, /api/login, /api/logout, /api/user
  setupAuth(app);
  
  // Stripe webhook handling (needs raw body)
  app.post('/api/webhooks', express.raw({ type: 'application/json' }), handleWebhook);
  
  // Create or get subscription for blaze plan
  app.post('/api/subscribe/blaze', async (req: Request, res: Response) => {
    if (!stripe) {
      return res.status(500).json({ message: 'Stripe not configured' });
    }
    
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      // Get admin settings
      const adminSetting = await storage.getAdminSettings();
      if (!adminSetting || !adminSetting.blazePriceId) {
        return res.status(500).json({ message: 'Subscription pricing not configured' });
      }
      
      // Check if user already has a customer ID
      let user = req.user;
      
      // If user already has a subscription, return current subscription info
      if (user.stripeSubscriptionId) {
        const subscription = await stripe.subscriptions.retrieve(user.stripeSubscriptionId);
        
        // Return the client secret from the latest invoice's payment intent
        if (subscription.status === 'active') {
          return res.json({
            subscriptionStatus: subscription.status,
            message: 'Subscription is already active',
          });
        }
        
        if (subscription.latest_invoice && typeof subscription.latest_invoice !== 'string') {
          const paymentIntent = subscription.latest_invoice.payment_intent;
          if (paymentIntent && typeof paymentIntent !== 'string') {
            return res.json({
              subscriptionId: subscription.id,
              clientSecret: paymentIntent.client_secret,
            });
          }
        }
      }
      
      // Create a new customer if needed
      let customerId = user.stripeCustomerId;
      if (!customerId) {
        const customer = await stripe.customers.create({
          email: user.email,
          name: user.username,
          metadata: {
            userId: user.id.toString()
          }
        });
        customerId = customer.id;
      }
      
      // Create the subscription
      const subscription = await stripe.subscriptions.create({
        customer: customerId,
        items: [{
          price: adminSetting.blazePriceId,
        }],
        payment_behavior: 'default_incomplete',
        payment_settings: {
          save_default_payment_method: 'on_subscription',
        },
        expand: ['latest_invoice.payment_intent'],
        metadata: {
          userId: user.id.toString()
        }
      });
      
      // Update user with stripe info
      await storage.updateStripeInfo(user.id, customerId, subscription.id);
      
      // Get the client secret
      if (
        subscription.latest_invoice &&
        typeof subscription.latest_invoice !== 'string' &&
        subscription.latest_invoice.payment_intent &&
        typeof subscription.latest_invoice.payment_intent !== 'string'
      ) {
        return res.json({
          subscriptionId: subscription.id,
          clientSecret: subscription.latest_invoice.payment_intent.client_secret,
        });
      } else {
        return res.status(500).json({ message: 'Failed to create subscription payment intent' });
      }
    } catch (error: any) {
      console.error('Subscription error:', error);
      return res.status(500).json({ message: `Subscription error: ${error.message}` });
    }
  });
  
  // Create or get subscription for inferno plan
  app.post('/api/subscribe/inferno', async (req: Request, res: Response) => {
    if (!stripe) {
      return res.status(500).json({ message: 'Stripe not configured' });
    }
    
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      // Get admin settings
      const adminSetting = await storage.getAdminSettings();
      if (!adminSetting || !adminSetting.infernoPriceId) {
        return res.status(500).json({ message: 'Subscription pricing not configured' });
      }
      
      // Check if user already has a customer ID
      let user = req.user;
      
      // If user already has a subscription, update it instead
      if (user.stripeSubscriptionId) {
        const subscription = await stripe.subscriptions.retrieve(user.stripeSubscriptionId);
        
        // If already on inferno plan, return current subscription info
        if (subscription.status === 'active') {
          const items = subscription.items.data;
          const priceId = items[0]?.price.id;
          
          if (priceId === adminSetting.infernoPriceId) {
            return res.json({
              subscriptionStatus: subscription.status,
              message: 'Already subscribed to Inferno plan',
            });
          }
          
          // Otherwise upgrade plan
          await stripe.subscriptions.update(subscription.id, {
            items: [{
              id: items[0]?.id,
              price: adminSetting.infernoPriceId,
            }],
            proration_behavior: 'always_invoice',
          });
          
          return res.json({
            subscriptionStatus: 'updated',
            message: 'Successfully upgraded to Inferno plan',
          });
        }
      }
      
      // Create a new customer if needed
      let customerId = user.stripeCustomerId;
      if (!customerId) {
        const customer = await stripe.customers.create({
          email: user.email,
          name: user.username,
          metadata: {
            userId: user.id.toString()
          }
        });
        customerId = customer.id;
      }
      
      // Create the subscription
      const subscription = await stripe.subscriptions.create({
        customer: customerId,
        items: [{
          price: adminSetting.infernoPriceId,
        }],
        payment_behavior: 'default_incomplete',
        payment_settings: {
          save_default_payment_method: 'on_subscription',
        },
        expand: ['latest_invoice.payment_intent'],
        metadata: {
          userId: user.id.toString()
        }
      });
      
      // Update user with stripe info and plan
      await storage.updateUser(user.id, {
        stripeCustomerId: customerId,
        stripeSubscriptionId: subscription.id,
        plan: 'inferno'
      });
      
      // Get the client secret
      if (
        subscription.latest_invoice &&
        typeof subscription.latest_invoice !== 'string' &&
        subscription.latest_invoice.payment_intent &&
        typeof subscription.latest_invoice.payment_intent !== 'string'
      ) {
        return res.json({
          subscriptionId: subscription.id,
          clientSecret: subscription.latest_invoice.payment_intent.client_secret,
        });
      } else {
        return res.status(500).json({ message: 'Failed to create subscription payment intent' });
      }
    } catch (error: any) {
      console.error('Subscription error:', error);
      return res.status(500).json({ message: `Subscription error: ${error.message}` });
    }
  });
  
  // Get user subscription info
  app.get('/api/subscription', async (req: Request, res: Response) => {
    if (!stripe) {
      return res.status(500).json({ message: 'Stripe not configured' });
    }
    
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const user = req.user;
      
      if (!user.stripeSubscriptionId) {
        return res.json({ 
          status: 'none',
          plan: user.plan,
        });
      }
      
      const subscription = await stripe.subscriptions.retrieve(user.stripeSubscriptionId);
      
      return res.json({
        status: subscription.status,
        plan: user.plan,
        currentPeriodEnd: new Date(subscription.current_period_end * 1000),
        cancelAtPeriodEnd: subscription.cancel_at_period_end,
      });
    } catch (error: any) {
      console.error('Error fetching subscription:', error);
      return res.status(500).json({ message: `Error fetching subscription: ${error.message}` });
    }
  });
  
  // Cancel subscription
  app.post('/api/subscription/cancel', async (req: Request, res: Response) => {
    if (!stripe) {
      return res.status(500).json({ message: 'Stripe not configured' });
    }
    
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const user = req.user;
      
      if (!user.stripeSubscriptionId) {
        return res.status(400).json({ message: 'No active subscription found' });
      }
      
      // Cancel at period end
      await stripe.subscriptions.update(user.stripeSubscriptionId, {
        cancel_at_period_end: true,
      });
      
      return res.json({ message: 'Subscription will be canceled at the end of the billing period' });
    } catch (error: any) {
      console.error('Error canceling subscription:', error);
      return res.status(500).json({ message: `Error canceling subscription: ${error.message}` });
    }
  });
  
  // Resume canceled subscription
  app.post('/api/subscription/resume', async (req: Request, res: Response) => {
    if (!stripe) {
      return res.status(500).json({ message: 'Stripe not configured' });
    }
    
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const user = req.user;
      
      if (!user.stripeSubscriptionId) {
        return res.status(400).json({ message: 'No subscription found' });
      }
      
      // Cancel at period end
      await stripe.subscriptions.update(user.stripeSubscriptionId, {
        cancel_at_period_end: false,
      });
      
      return res.json({ message: 'Subscription has been resumed' });
    } catch (error: any) {
      console.error('Error resuming subscription:', error);
      return res.status(500).json({ message: `Error resuming subscription: ${error.message}` });
    }
  });
  
  // Content generation endpoint
  app.post('/api/content/generate', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const { prompt, contentType, tone, length } = req.body;
      
      if (!prompt || !contentType) {
        return res.status(400).json({ message: 'Missing required parameters' });
      }
      
      const generatedContent = await openai.generateContent({
        prompt,
        contentType,
        tone,
        length
      });
      
      return res.json(generatedContent);
    } catch (error: any) {
      console.error('Content generation error:', error);
      return res.status(500).json({ message: `Content generation error: ${error.message}` });
    }
  });
  
  // Save content endpoint
  app.post('/api/content', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const { title, textContent, imageUrl, contentType } = req.body;
      
      if (!title || !contentType) {
        return res.status(400).json({ message: 'Missing required parameters' });
      }
      
      const content = await storage.createContent({
        userId: req.user.id,
        title,
        textContent,
        imageUrl,
        contentType,
        status: 'draft'
      });
      
      return res.status(201).json(content);
    } catch (error: any) {
      console.error('Error saving content:', error);
      return res.status(500).json({ message: `Error saving content: ${error.message}` });
    }
  });
  
  // Get content by ID
  app.get('/api/content/:id', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const contentId = parseInt(req.params.id);
      if (isNaN(contentId)) {
        return res.status(400).json({ message: 'Invalid content ID' });
      }
      
      const content = await storage.getContent(contentId);
      
      if (!content) {
        return res.status(404).json({ message: 'Content not found' });
      }
      
      // Check ownership
      if (content.userId !== req.user.id && !req.user.isAdmin) {
        return res.status(403).json({ message: 'Not authorized to access this content' });
      }
      
      return res.json(content);
    } catch (error: any) {
      console.error('Error fetching content:', error);
      return res.status(500).json({ message: `Error fetching content: ${error.message}` });
    }
  });
  
  // Get user contents
  app.get('/api/contents', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const limit = req.query.limit ? parseInt(req.query.limit as string) : undefined;
      const contents = await storage.getUserContents(req.user.id, limit);
      
      return res.json(contents);
    } catch (error: any) {
      console.error('Error fetching contents:', error);
      return res.status(500).json({ message: `Error fetching contents: ${error.message}` });
    }
  });
  
  // Update content
  app.put('/api/content/:id', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const contentId = parseInt(req.params.id);
      if (isNaN(contentId)) {
        return res.status(400).json({ message: 'Invalid content ID' });
      }
      
      // Get content
      const content = await storage.getContent(contentId);
      
      if (!content) {
        return res.status(404).json({ message: 'Content not found' });
      }
      
      // Check ownership
      if (content.userId !== req.user.id && !req.user.isAdmin) {
        return res.status(403).json({ message: 'Not authorized to update this content' });
      }
      
      // Update content
      const { title, textContent, imageUrl, status } = req.body;
      const updatedContent = await storage.updateContent(contentId, {
        title,
        textContent,
        imageUrl,
        status
      });
      
      return res.json(updatedContent);
    } catch (error: any) {
      console.error('Error updating content:', error);
      return res.status(500).json({ message: `Error updating content: ${error.message}` });
    }
  });
  
  // Delete content
  app.delete('/api/content/:id', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const contentId = parseInt(req.params.id);
      if (isNaN(contentId)) {
        return res.status(400).json({ message: 'Invalid content ID' });
      }
      
      // Get content
      const content = await storage.getContent(contentId);
      
      if (!content) {
        return res.status(404).json({ message: 'Content not found' });
      }
      
      // Check ownership
      if (content.userId !== req.user.id && !req.user.isAdmin) {
        return res.status(403).json({ message: 'Not authorized to delete this content' });
      }
      
      // Delete content
      await storage.deleteContent(contentId);
      
      return res.json({ success: true });
    } catch (error: any) {
      console.error('Error deleting content:', error);
      return res.status(500).json({ message: `Error deleting content: ${error.message}` });
    }
  });
  
  // Schedule content
  app.post('/api/schedule', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const { contentId, platform, scheduledDate } = req.body;
      
      if (!contentId || !platform || !scheduledDate) {
        return res.status(400).json({ message: 'Missing required parameters' });
      }
      
      // Check content exists and belongs to user
      const content = await storage.getContent(contentId);
      
      if (!content) {
        return res.status(404).json({ message: 'Content not found' });
      }
      
      if (content.userId !== req.user.id && !req.user.isAdmin) {
        return res.status(403).json({ message: 'Not authorized to schedule this content' });
      }
      
      // Create schedule
      const schedule = await storage.createSchedule({
        contentId,
        platform,
        scheduledDate: new Date(scheduledDate)
      });
      
      // Update content status to scheduled
      await storage.updateContent(contentId, { status: 'scheduled' });
      
      return res.status(201).json(schedule);
    } catch (error: any) {
      console.error('Error scheduling content:', error);
      return res.status(500).json({ message: `Error scheduling content: ${error.message}` });
    }
  });
  
  // Get upcoming schedules
  app.get('/api/schedules/upcoming', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const limit = req.query.limit ? parseInt(req.query.limit as string) : undefined;
      const schedules = await storage.getUpcomingSchedules(req.user.id, limit);
      
      return res.json(schedules);
    } catch (error: any) {
      console.error('Error fetching schedules:', error);
      return res.status(500).json({ message: `Error fetching schedules: ${error.message}` });
    }
  });
  
  // Get content stats
  app.get('/api/stats', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const stats = await storage.getContentStats(req.user.id);
      return res.json(stats);
    } catch (error: any) {
      console.error('Error fetching stats:', error);
      return res.status(500).json({ message: `Error fetching stats: ${error.message}` });
    }
  });
  
  // Company profile endpoints
  app.get('/api/company-profile', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const profile = await storage.getCompanyProfile(req.user.id);
      if (!profile) {
        return res.status(404).json({ message: 'No company profile found' });
      }
      res.json(profile);
    } catch (error: any) {
      console.error('Error fetching company profile:', error);
      return res.status(500).json({ message: `Error fetching company profile: ${error.message}` });
    }
  });
  
  app.post('/api/company-profile', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const profileData = insertCompanyProfileSchema.parse(req.body);
      
      // Check if profile already exists
      const existingProfile = await storage.getCompanyProfile(req.user.id);
      
      let profile;
      if (existingProfile) {
        profile = await storage.updateCompanyProfile(existingProfile.id, profileData);
      } else {
        profile = await storage.createCompanyProfile({
          ...profileData,
          userId: req.user.id
        });
      }
      
      res.status(201).json(profile);
    } catch (error: any) {
      console.error('Error creating/updating company profile:', error);
      return res.status(400).json({ message: `Error creating/updating company profile: ${error.message}` });
    }
  });
  
  app.put('/api/company-profile/:id', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const id = parseInt(req.params.id);
      const profileData = req.body;
      
      // Get profile to verify ownership
      const profile = await storage.getCompanyProfile(req.user.id);
      if (!profile || profile.id !== id) {
        return res.status(404).json({ message: 'Profile not found or unauthorized' });
      }
      
      const updatedProfile = await storage.updateCompanyProfile(id, profileData);
      res.json(updatedProfile);
    } catch (error: any) {
      console.error('Error updating company profile:', error);
      return res.status(400).json({ message: `Error updating company profile: ${error.message}` });
    }
  });
  
  // Admin routes
  app.get('/api/admin/settings', async (req: Request, res: Response) => {
    if (!req.isAuthenticated() || !req.user.isAdmin) {
      return res.status(403).json({ message: 'Not authorized' });
    }
    
    try {
      let settings = await storage.getAdminSettings();
      
      // If no settings exist, create default settings
      if (!settings) {
        settings = await storage.createOrUpdateAdminSettings({
          infernoPrice: 19900, // $199.00
          blazePrice: 9900,    // $99.00
          selfPromoEnabled: true,
          selfPromoInterval: 7
        });
      }
      
      return res.json(settings);
    } catch (error: any) {
      console.error('Error fetching admin settings:', error);
      return res.status(500).json({ message: `Error fetching admin settings: ${error.message}` });
    }
  });
  
  app.post('/api/admin/settings', async (req: Request, res: Response) => {
    if (!req.isAuthenticated() || !req.user.isAdmin) {
      return res.status(403).json({ message: 'Not authorized' });
    }
    
    try {
      const { infernoPrice, blazePrice, selfPromoEnabled, selfPromoInterval, stripeProductId, blazePriceId, infernoPriceId } = req.body;
      
      const settings = await storage.createOrUpdateAdminSettings({
        infernoPrice,
        blazePrice,
        selfPromoEnabled,
        selfPromoInterval,
        stripeProductId,
        blazePriceId,
        infernoPriceId
      });
      
      return res.json(settings);
    } catch (error: any) {
      console.error('Error updating admin settings:', error);
      return res.status(500).json({ message: `Error updating admin settings: ${error.message}` });
    }
  });
  
  // Create a Stripe product and price for subscriptions
  app.post('/api/admin/setup-stripe', async (req: Request, res: Response) => {
    if (!stripe) {
      return res.status(500).json({ message: 'Stripe not configured' });
    }
    
    if (!req.isAuthenticated() || !req.user.isAdmin) {
      return res.status(403).json({ message: 'Not authorized' });
    }
    
    try {
      // Get current settings
      let settings = await storage.getAdminSettings();
      
      // If no settings exist, create default settings
      if (!settings) {
        settings = await storage.createOrUpdateAdminSettings({
          infernoPrice: 19900, // $199.00
          blazePrice: 9900,    // $99.00
          selfPromoEnabled: true,
          selfPromoInterval: 7
        });
      }
      
      // Create or get product
      let productId = settings.stripeProductId;
      
      if (!productId) {
        const product = await stripe.products.create({
          name: 'Kontent Fire Subscription',
          description: 'AI-powered content generation platform subscription'
        });
        productId = product.id;
      }
      
      // Create or update Blaze price
      let blazePriceId = settings.blazePriceId;
      
      if (!blazePriceId) {
        const blazePrice = await stripe.prices.create({
          product: productId,
          unit_amount: settings.blazePrice,
          currency: 'usd',
          recurring: {
            interval: 'month'
          },
          nickname: 'Blaze Plan'
        });
        blazePriceId = blazePrice.id;
      }
      
      // Create or update Inferno price
      let infernoPriceId = settings.infernoPriceId;
      
      if (!infernoPriceId) {
        const infernoPrice = await stripe.prices.create({
          product: productId,
          unit_amount: settings.infernoPrice,
          currency: 'usd',
          recurring: {
            interval: 'month'
          },
          nickname: 'Inferno Plan'
        });
        infernoPriceId = infernoPrice.id;
      }
      
      // Update settings with IDs
      const updatedSettings = await storage.createOrUpdateAdminSettings({
        ...settings,
        stripeProductId: productId,
        blazePriceId,
        infernoPriceId
      });
      
      return res.json({
        message: 'Stripe products and prices created successfully',
        settings: updatedSettings
      });
    } catch (error: any) {
      console.error('Error setting up Stripe:', error);
      return res.status(500).json({ message: `Error setting up Stripe: ${error.message}` });
    }
  });
  
  // Get all users (admin only)
  app.get('/api/admin/users', async (req: Request, res: Response) => {
    if (!req.isAuthenticated() || !req.user.isAdmin) {
      return res.status(403).json({ message: 'Not authorized' });
    }
    
    try {
      const allUsers = await db.select({
        id: users.id,
        username: users.username,
        email: users.email,
        createdAt: users.createdAt,
        plan: users.plan,
        stripeCustomerId: users.stripeCustomerId,
        stripeSubscriptionId: users.stripeSubscriptionId,
        isAdmin: users.isAdmin
      }).from(users);
      
      return res.json(allUsers);
    } catch (error: any) {
      console.error('Error fetching users:', error);
      return res.status(500).json({ message: `Error fetching users: ${error.message}` });
    }
  });
  
  // Update user plan (admin only)
  app.put('/api/admin/users/:id/plan', async (req: Request, res: Response) => {
    if (!req.isAuthenticated() || !req.user.isAdmin) {
      return res.status(403).json({ message: 'Not authorized' });
    }
    
    try {
      const userId = parseInt(req.params.id);
      const { plan } = req.body;
      
      if (!userId || !plan) {
        return res.status(400).json({ message: 'Missing required parameters' });
      }
      
      const user = await storage.updateUser(userId, { plan });
      
      return res.json({
        message: `User plan updated to ${plan}`,
        user
      });
    } catch (error: any) {
      console.error('Error updating user plan:', error);
      return res.status(500).json({ message: `Error updating user plan: ${error.message}` });
    }
  });
  
  // Create admin user
  app.post('/api/admin/create-admin', async (req, res) => {
    // Only allow this endpoint if no admin exists yet
    const adminCount = await db.select({ count: sql`count(*)` })
      .from(users)
      .where(eq(users.isAdmin, true));
      
    if (adminCount[0].count > 0) {
      return res.status(403).json({ message: 'Admin already exists' });
    }
    
    const { username, email, password } = req.body;
    
    if (!username || !email || !password) {
      return res.status(400).json({ message: 'Missing required fields' });
    }
    
    try {
      // Create admin user
      const hashedPassword = await hashPassword(password);
      
      const user = await db.insert(users)
        .values({
          username,
          email,
          password: hashedPassword,
          isAdmin: true,
          plan: 'inferno'
        })
        .returning();
      
      // Create default admin settings
      await db.insert(adminSettings)
        .values({
          infernoPrice: 19900, // $199.00
          blazePrice: 9900,    // $99.00
          selfPromoEnabled: true,
          selfPromoInterval: 7
        })
        .onConflictDoNothing();
      
      return res.json({ message: 'Admin created successfully' });
    } catch (error: any) {
      console.error('Error creating admin:', error);
      return res.status(500).json({ message: `Error creating admin: ${error.message}` });
    }
  });
  
  // Content repurposing endpoint
  app.post('/api/content/repurpose', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const { content, title, sourcePlatform, targetPlatform, tone, additionalInstructions } = req.body as RepurposeRequest;
      
      if (!content || !sourcePlatform || !targetPlatform) {
        return res.status(400).json({ message: 'Missing required parameters' });
      }
      
      // Check user plan - make available to all plans
      // This feature is available to all plans as it's a core content creation feature
      
      const result = await repurposeContent({
        content, 
        title, 
        sourcePlatform, 
        targetPlatform, 
        tone, 
        additionalInstructions
      });
      
      return res.json(result);
    } catch (error: any) {
      console.error('Content repurposing error:', error);
      return res.status(500).json({ 
        message: `Error during content repurposing: ${error.message}` 
      });
    }
  });

  // Fact-checking endpoint
  app.post('/api/fact-check', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const { text, context } = req.body as FactCheckRequest;
      
      if (!text) {
        return res.status(400).json({ message: 'Missing required text parameter' });
      }
      
      // Check user plan
      const user = req.user;
      if (user.plan !== 'inferno') {
        return res.status(403).json({ 
          message: 'This feature requires the Inferno plan',
          upgradeRequired: true 
        });
      }
      
      const result = await factCheck({ text, context });
      return res.json(result);
    } catch (error: any) {
      console.error('Fact-checking error:', error);
      return res.status(500).json({ 
        message: `Error during fact-checking: ${error.message}` 
      });
    }
  });
  
  // References search endpoint
  app.post('/api/references', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const { query, count } = req.body as ReferencesRequest;
      
      if (!query) {
        return res.status(400).json({ message: 'Missing required query parameter' });
      }
      
      // Check user plan
      const user = req.user;
      if (user.plan !== 'inferno') {
        return res.status(403).json({ 
          message: 'This feature requires the Inferno plan',
          upgradeRequired: true 
        });
      }
      
      const result = await getReferences({ query, count });
      return res.json(result);
    } catch (error: any) {
      console.error('References search error:', error);
      return res.status(500).json({ 
        message: `Error during references search: ${error.message}` 
      });
    }
  });

  // AUTO CONTENT ENDPOINTS
  
  // Get auto content configuration
  app.get('/api/auto-content/config', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const user = req.user;
      
      // Check if user is on Inferno plan for this premium feature
      if (user.plan !== 'inferno') {
        return res.status(403).json({ 
          message: 'Automatic content feature requires Inferno plan',
          upgrade: true 
        });
      }
      
      // Check if configuration exists for user
      const [config] = await db.select()
        .from(autoContentConfigs)
        .where(eq(autoContentConfigs.userId, user.id));
      
      if (!config) {
        return res.status(404).json({ message: 'Configuration not found' });
      }
      
      return res.json(config);
    } catch (error: any) {
      console.error('Error fetching auto content config:', error);
      return res.status(500).json({ message: `Error fetching configuration: ${error.message}` });
    }
  });
  
  // Create auto content configuration
  app.post('/api/auto-content/config', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const user = req.user;
      
      // Check if user is on Inferno plan for this premium feature
      if (user.plan !== 'inferno') {
        return res.status(403).json({ 
          message: 'Automatic content feature requires Inferno plan',
          upgrade: true 
        });
      }
      
      // Check if configuration already exists
      const [existingConfig] = await db.select()
        .from(autoContentConfigs)
        .where(eq(autoContentConfigs.userId, user.id));
        
      if (existingConfig) {
        return res.status(400).json({ message: 'Configuration already exists, use PUT to update' });
      }
      
      // Validate request body
      const configData = insertAutoContentConfigSchema.parse({
        ...req.body,
        userId: user.id
      });
      
      // Create configuration
      const [config] = await db.insert(autoContentConfigs)
        .values(configData)
        .returning();
      
      return res.status(201).json(config);
    } catch (error: any) {
      console.error('Error creating auto content config:', error);
      return res.status(500).json({ message: `Error creating configuration: ${error.message}` });
    }
  });
  
  // Update auto content configuration
  app.put('/api/auto-content/config', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const user = req.user;
      
      // Check if user is on Inferno plan for this premium feature
      if (user.plan !== 'inferno') {
        return res.status(403).json({ 
          message: 'Automatic content feature requires Inferno plan',
          upgrade: true 
        });
      }
      
      // Check if configuration exists
      const [existingConfig] = await db.select()
        .from(autoContentConfigs)
        .where(eq(autoContentConfigs.userId, user.id));
        
      if (!existingConfig) {
        return res.status(404).json({ message: 'Configuration not found, use POST to create' });
      }
      
      // Update configuration
      const [config] = await db.update(autoContentConfigs)
        .set({
          ...req.body,
          updatedAt: new Date()
        })
        .where(eq(autoContentConfigs.userId, user.id))
        .returning();
      
      return res.json(config);
    } catch (error: any) {
      console.error('Error updating auto content config:', error);
      return res.status(500).json({ message: `Error updating configuration: ${error.message}` });
    }
  });
  
  // Get upcoming auto-generated content schedule
  app.get('/api/auto-content/schedules/upcoming', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const user = req.user;
      
      // Check if user is on Inferno plan for this premium feature
      if (user.plan !== 'inferno') {
        return res.status(403).json({ 
          message: 'Automatic content feature requires Inferno plan',
          upgrade: true 
        });
      }
      
      // Get upcoming (pending) scheduled content
      const scheduledContent = await storage.getUpcomingAutoContent(user.id);
      
      return res.json(scheduledContent);
    } catch (error: any) {
      console.error('Error fetching upcoming auto content:', error);
      return res.status(500).json({ message: `Error fetching upcoming auto content: ${error.message}` });
    }
  });
  
  // Get history of auto-generated content (published or failed)
  app.get('/api/auto-content/schedules/history', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const user = req.user;
      
      // Check if user is on Inferno plan for this premium feature
      if (user.plan !== 'inferno') {
        return res.status(403).json({ 
          message: 'Automatic content feature requires Inferno plan',
          upgrade: true 
        });
      }
      
      // Get history of scheduled content (published or failed)
      const contentHistory = await storage.getAutoContentHistory(user.id);
      
      return res.json(contentHistory);
    } catch (error: any) {
      console.error('Error fetching auto content history:', error);
      return res.status(500).json({ message: `Error fetching auto content history: ${error.message}` });
    }
  });
  
  // Cancel scheduled auto-generated content
  app.delete('/api/auto-content/schedule/:id', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const user = req.user;
      const scheduleId = parseInt(req.params.id);
      
      if (isNaN(scheduleId)) {
        return res.status(400).json({ message: 'Invalid schedule ID' });
      }
      
      // Check if user is on Inferno plan for this premium feature
      if (user.plan !== 'inferno') {
        return res.status(403).json({ 
          message: 'Automatic content feature requires Inferno plan',
          upgrade: true 
        });
      }
      
      try {
        // Cancel auto content through the storage interface
        await storage.cancelAutoContent(scheduleId);
      } catch (error) {
        return res.status(400).json({ message: 'Cannot cancel this scheduled content' });
      }
      
      return res.json({ message: 'Scheduled content canceled successfully' });
    } catch (error: any) {
      console.error('Error canceling scheduled content:', error);
      return res.status(500).json({ message: `Error canceling scheduled content: ${error.message}` });
    }
  });
  
  /***********************************************
   * BUSINESS LISTINGS MANAGEMENT API ENDPOINTS
   ***********************************************/
  
  // Get company business hours
  app.get('/api/business-hours', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      // First get the company profile
      const profile = await storage.getCompanyProfile(req.user.id);
      
      if (!profile) {
        return res.status(404).json({ message: 'Company profile not found. Please create a profile first.' });
      }
      
      // Get the business hours
      const hours = await storage.getBusinessHours(profile.id);
      
      return res.json(hours || null);
    } catch (error: any) {
      console.error('Error fetching business hours:', error);
      return res.status(500).json({ message: `Error fetching business hours: ${error.message}` });
    }
  });
  
  // Create or update business hours
  app.post('/api/business-hours', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      // Validate request
      const parsedData = insertBusinessHoursSchema.safeParse(req.body);
      if (!parsedData.success) {
        return res.status(400).json({ message: 'Invalid business hours data', errors: parsedData.error.format() });
      }
      
      // Get company profile
      const profile = await storage.getCompanyProfile(req.user.id);
      
      if (!profile) {
        return res.status(404).json({ message: 'Company profile not found. Please create a profile first.' });
      }
      
      // Check if hours already exist
      const existingHours = await storage.getBusinessHours(profile.id);
      
      let hours;
      
      if (existingHours) {
        // Update existing hours
        hours = await storage.updateBusinessHours(existingHours.id, {
          ...parsedData.data,
          updatedAt: new Date()
        });
      } else {
        // Create new hours
        hours = await storage.createBusinessHours({
          ...parsedData.data,
          companyProfileId: profile.id
        });
      }
      
      return res.status(201).json(hours);
    } catch (error: any) {
      console.error('Error saving business hours:', error);
      return res.status(500).json({ message: `Error saving business hours: ${error.message}` });
    }
  });
  
  // Get all user's business listings
  app.get('/api/business-listings', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const listings = await storage.getUserBusinessListings(req.user.id);
      return res.json(listings);
    } catch (error: any) {
      console.error('Error fetching business listings:', error);
      return res.status(500).json({ message: `Error fetching business listings: ${error.message}` });
    }
  });
  
  // Get a business listing by ID
  app.get('/api/business-listings/:id', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const listingId = parseInt(req.params.id);
      if (isNaN(listingId)) {
        return res.status(400).json({ message: 'Invalid listing ID' });
      }
      
      const listing = await storage.getBusinessListing(listingId);
      
      if (!listing) {
        return res.status(404).json({ message: 'Business listing not found' });
      }
      
      // Check ownership
      if (listing.userId !== req.user.id && !req.user.isAdmin) {
        return res.status(403).json({ message: 'Not authorized to access this listing' });
      }
      
      return res.json(listing);
    } catch (error: any) {
      console.error('Error fetching business listing:', error);
      return res.status(500).json({ message: `Error fetching business listing: ${error.message}` });
    }
  });
  
  // Create a new business listing
  app.post('/api/business-listings', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      // Validate request
      const parsedData = insertBusinessListingSchema.safeParse(req.body);
      if (!parsedData.success) {
        return res.status(400).json({ message: 'Invalid business listing data', errors: parsedData.error.format() });
      }
      
      // Get company profile
      const profile = await storage.getCompanyProfile(req.user.id);
      
      if (!profile) {
        return res.status(404).json({ message: 'Company profile not found. Please create a profile first.' });
      }
      
      // Check if a listing already exists for this platform
      const existingListing = await storage.getBusinessListingByPlatform(
        req.user.id, 
        parsedData.data.platform
      );
      
      if (existingListing) {
        return res.status(409).json({ 
          message: `A listing for ${parsedData.data.platform} already exists.`,
          listing: existingListing
        });
      }
      
      // Create the listing
      const listing = await storage.createBusinessListing({
        ...parsedData.data,
        userId: req.user.id,
        companyProfileId: profile.id
      });
      
      return res.status(201).json(listing);
    } catch (error: any) {
      console.error('Error creating business listing:', error);
      return res.status(500).json({ message: `Error creating business listing: ${error.message}` });
    }
  });
  
  // Update a business listing
  app.put('/api/business-listings/:id', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const listingId = parseInt(req.params.id);
      if (isNaN(listingId)) {
        return res.status(400).json({ message: 'Invalid listing ID' });
      }
      
      // Check if listing exists
      const listing = await storage.getBusinessListing(listingId);
      
      if (!listing) {
        return res.status(404).json({ message: 'Business listing not found' });
      }
      
      // Check ownership
      if (listing.userId !== req.user.id && !req.user.isAdmin) {
        return res.status(403).json({ message: 'Not authorized to update this listing' });
      }
      
      // Update the listing
      const updatedListing = await storage.updateBusinessListing(listingId, {
        ...req.body,
        updatedAt: new Date()
      });
      
      return res.json(updatedListing);
    } catch (error: any) {
      console.error('Error updating business listing:', error);
      return res.status(500).json({ message: `Error updating business listing: ${error.message}` });
    }
  });
  
  // Delete a business listing
  app.delete('/api/business-listings/:id', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const listingId = parseInt(req.params.id);
      if (isNaN(listingId)) {
        return res.status(400).json({ message: 'Invalid listing ID' });
      }
      
      // Check if listing exists
      const listing = await storage.getBusinessListing(listingId);
      
      if (!listing) {
        return res.status(404).json({ message: 'Business listing not found' });
      }
      
      // Check ownership
      if (listing.userId !== req.user.id && !req.user.isAdmin) {
        return res.status(403).json({ message: 'Not authorized to delete this listing' });
      }
      
      // Delete the listing
      await storage.deleteBusinessListing(listingId);
      
      return res.json({ message: 'Business listing deleted successfully' });
    } catch (error: any) {
      console.error('Error deleting business listing:', error);
      return res.status(500).json({ message: `Error deleting business listing: ${error.message}` });
    }
  });
  
  // Get sync tasks for a listing
  app.get('/api/business-listings/:id/tasks', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const listingId = parseInt(req.params.id);
      if (isNaN(listingId)) {
        return res.status(400).json({ message: 'Invalid listing ID' });
      }
      
      // Check if listing exists and belongs to user
      const listing = await storage.getBusinessListing(listingId);
      
      if (!listing) {
        return res.status(404).json({ message: 'Business listing not found' });
      }
      
      // Check ownership
      if (listing.userId !== req.user.id && !req.user.isAdmin) {
        return res.status(403).json({ message: 'Not authorized to access tasks for this listing' });
      }
      
      // Get tasks
      const tasks = await storage.getListingTasks(listingId);
      
      return res.json(tasks);
    } catch (error: any) {
      console.error('Error fetching listing tasks:', error);
      return res.status(500).json({ message: `Error fetching listing tasks: ${error.message}` });
    }
  });
  
  // Get all user's sync tasks
  app.get('/api/listing-tasks', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const status = req.query.status as string | undefined;
      const tasks = await storage.getUserListingSyncTasks(req.user.id, status);
      
      return res.json(tasks);
    } catch (error: any) {
      console.error('Error fetching listing tasks:', error);
      return res.status(500).json({ message: `Error fetching listing tasks: ${error.message}` });
    }
  });
  
  // Create a new sync task
  app.post('/api/listing-tasks', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      // Validate request
      const parsedData = insertListingSyncTaskSchema.safeParse(req.body);
      if (!parsedData.success) {
        return res.status(400).json({ message: 'Invalid task data', errors: parsedData.error.format() });
      }
      
      // If listing ID is provided, check it exists and belongs to user
      if (parsedData.data.listingId) {
        const listing = await storage.getBusinessListing(parsedData.data.listingId);
        
        if (!listing) {
          return res.status(404).json({ message: 'Business listing not found' });
        }
        
        if (listing.userId !== req.user.id && !req.user.isAdmin) {
          return res.status(403).json({ message: 'Not authorized to create tasks for this listing' });
        }
      }
      
      // Create the task
      const task = await storage.createListingSyncTask({
        ...parsedData.data,
        userId: req.user.id
      });
      
      return res.status(201).json(task);
    } catch (error: any) {
      console.error('Error creating listing task:', error);
      return res.status(500).json({ message: `Error creating listing task: ${error.message}` });
    }
  });
  
  // Mark a task as completed
  app.post('/api/listing-tasks/:id/complete', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const taskId = parseInt(req.params.id);
      if (isNaN(taskId)) {
        return res.status(400).json({ message: 'Invalid task ID' });
      }
      
      // Check if task exists
      const task = await storage.getListingSyncTask(taskId);
      
      if (!task) {
        return res.status(404).json({ message: 'Task not found' });
      }
      
      // Check ownership
      if (task.userId !== req.user.id && !req.user.isAdmin) {
        return res.status(403).json({ message: 'Not authorized to update this task' });
      }
      
      // Mark as completed
      const completedTask = await storage.markTaskCompleted(taskId);
      
      return res.json(completedTask);
    } catch (error: any) {
      console.error('Error completing task:', error);
      return res.status(500).json({ message: `Error completing task: ${error.message}` });
    }
  });
  
  // Get all reviews for a business listing
  app.get('/api/business-listings/:id/reviews', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const listingId = parseInt(req.params.id);
      if (isNaN(listingId)) {
        return res.status(400).json({ message: 'Invalid listing ID' });
      }
      
      // Check if listing exists and belongs to user
      const listing = await storage.getBusinessListing(listingId);
      
      if (!listing) {
        return res.status(404).json({ message: 'Business listing not found' });
      }
      
      // Check ownership
      if (listing.userId !== req.user.id && !req.user.isAdmin) {
        return res.status(403).json({ message: 'Not authorized to access reviews for this listing' });
      }
      
      // Get reviews
      const reviews = await storage.getListingReviews(listingId);
      
      return res.json(reviews);
    } catch (error: any) {
      console.error('Error fetching reviews:', error);
      return res.status(500).json({ message: `Error fetching reviews: ${error.message}` });
    }
  });
  
  // Get all user's reviews (optionally filtered by platform)
  app.get('/api/business-reviews', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const platform = req.query.platform as string | undefined;
      const reviews = await storage.getUserBusinessReviews(req.user.id, platform);
      
      return res.json(reviews);
    } catch (error: any) {
      console.error('Error fetching reviews:', error);
      return res.status(500).json({ message: `Error fetching reviews: ${error.message}` });
    }
  });
  
  // Add a response to a review
  app.post('/api/business-reviews/:id/respond', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const reviewId = parseInt(req.params.id);
      if (isNaN(reviewId)) {
        return res.status(400).json({ message: 'Invalid review ID' });
      }
      
      const { responseText } = req.body;
      
      if (!responseText) {
        return res.status(400).json({ message: 'Response text is required' });
      }
      
      // Check if review exists
      const review = await storage.getBusinessReview(reviewId);
      
      if (!review) {
        return res.status(404).json({ message: 'Review not found' });
      }
      
      // Check ownership
      if (review.userId !== req.user.id && !req.user.isAdmin) {
        return res.status(403).json({ message: 'Not authorized to respond to this review' });
      }
      
      // Add response
      const updatedReview = await storage.respondToReview(reviewId, responseText);
      
      return res.json(updatedReview);
    } catch (error: any) {
      console.error('Error responding to review:', error);
      return res.status(500).json({ message: `Error responding to review: ${error.message}` });
    }
  });
  
  // Get listings stats for analytics
  app.get('/api/analytics/listings', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const stats = await storage.getListingsStats(req.user.id);
      return res.json(stats);
    } catch (error: any) {
      console.error('Error fetching listings stats:', error);
      return res.status(500).json({ message: `Error fetching listings stats: ${error.message}` });
    }
  });

  // Company profile endpoints
  app.get('/api/company-profile', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const profile = await storage.getCompanyProfile(req.user.id);
      return res.json(profile || null);
    } catch (error: any) {
      console.error('Error fetching company profile:', error);
      return res.status(500).json({ message: `Error fetching company profile: ${error.message}` });
    }
  });

  app.post('/api/company-profile', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const validatedData = insertCompanyProfileSchema.parse({
        ...req.body,
        userId: req.user.id
      });
      
      const profile = await storage.createCompanyProfile(validatedData);
      return res.status(201).json(profile);
    } catch (error: any) {
      console.error('Error creating company profile:', error);
      return res.status(500).json({ message: `Error creating company profile: ${error.message}` });
    }
  });

  app.put('/api/company-profile/:id', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const profileId = parseInt(req.params.id);
      if (isNaN(profileId)) {
        return res.status(400).json({ message: 'Invalid profile ID' });
      }
      
      // Update profile
      const profile = await storage.updateCompanyProfile(profileId, req.body);
      return res.json(profile);
    } catch (error: any) {
      console.error('Error updating company profile:', error);
      return res.status(500).json({ message: `Error updating company profile: ${error.message}` });
    }
  });

  // Business listings endpoints
  app.get('/api/business-listings', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const listings = await storage.getUserBusinessListings(req.user.id);
      return res.json(listings);
    } catch (error: any) {
      console.error('Error fetching business listings:', error);
      return res.status(500).json({ message: `Error fetching business listings: ${error.message}` });
    }
  });

  app.post('/api/business-listings', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      // Get company profile
      const profile = await storage.getCompanyProfile(req.user.id);
      if (!profile) {
        return res.status(400).json({ message: 'Company profile must be created first' });
      }
      
      // Validate and create listing
      const validatedData = insertBusinessListingSchema.parse({
        ...req.body,
        userId: req.user.id,
        companyProfileId: profile.id
      });
      
      const listing = await storage.createBusinessListing(validatedData);
      
      // Create initial verification task if needed
      if (req.body.platform && !req.body.verificationStatus) {
        await storage.createListingSyncTask({
          userId: req.user.id,
          listingId: listing.id,
          platform: req.body.platform,
          taskType: 'Verification',
          taskDescription: `Verify your business listing on ${req.body.platform}`,
          status: 'pending',
          dueDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000) // 7 days from now
        });
      }
      
      return res.status(201).json(listing);
    } catch (error: any) {
      console.error('Error creating business listing:', error);
      return res.status(500).json({ message: `Error creating business listing: ${error.message}` });
    }
  });

  app.get('/api/business-listings/:id', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const listingId = parseInt(req.params.id);
      if (isNaN(listingId)) {
        return res.status(400).json({ message: 'Invalid listing ID' });
      }
      
      const listing = await storage.getBusinessListing(listingId);
      
      if (!listing) {
        return res.status(404).json({ message: 'Listing not found' });
      }
      
      // Check ownership
      if (listing.userId !== req.user.id && !req.user.isAdmin) {
        return res.status(403).json({ message: 'Not authorized to access this listing' });
      }
      
      return res.json(listing);
    } catch (error: any) {
      console.error('Error fetching business listing:', error);
      return res.status(500).json({ message: `Error fetching business listing: ${error.message}` });
    }
  });

  app.put('/api/business-listings/:id', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const listingId = parseInt(req.params.id);
      if (isNaN(listingId)) {
        return res.status(400).json({ message: 'Invalid listing ID' });
      }
      
      // Get listing to check ownership
      const listing = await storage.getBusinessListing(listingId);
      
      if (!listing) {
        return res.status(404).json({ message: 'Listing not found' });
      }
      
      if (listing.userId !== req.user.id && !req.user.isAdmin) {
        return res.status(403).json({ message: 'Not authorized to update this listing' });
      }
      
      // Update listing
      const updatedListing = await storage.updateBusinessListing(listingId, req.body);
      return res.json(updatedListing);
    } catch (error: any) {
      console.error('Error updating business listing:', error);
      return res.status(500).json({ message: `Error updating business listing: ${error.message}` });
    }
  });

  app.delete('/api/business-listings/:id', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const listingId = parseInt(req.params.id);
      if (isNaN(listingId)) {
        return res.status(400).json({ message: 'Invalid listing ID' });
      }
      
      // Get listing to check ownership
      const listing = await storage.getBusinessListing(listingId);
      
      if (!listing) {
        return res.status(404).json({ message: 'Listing not found' });
      }
      
      if (listing.userId !== req.user.id && !req.user.isAdmin) {
        return res.status(403).json({ message: 'Not authorized to delete this listing' });
      }
      
      // Delete listing
      await storage.deleteBusinessListing(listingId);
      return res.json({ success: true });
    } catch (error: any) {
      console.error('Error deleting business listing:', error);
      return res.status(500).json({ message: `Error deleting business listing: ${error.message}` });
    }
  });

  // Listing tasks endpoints
  app.get('/api/listing-tasks', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const status = req.query.status as string;
      const tasks = await storage.getUserListingSyncTasks(req.user.id, status);
      return res.json(tasks);
    } catch (error: any) {
      console.error('Error fetching listing tasks:', error);
      return res.status(500).json({ message: `Error fetching listing tasks: ${error.message}` });
    }
  });

  app.post('/api/listing-tasks', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      // Validate and create task
      const validatedData = insertListingSyncTaskSchema.parse({
        ...req.body,
        userId: req.user.id
      });
      
      const task = await storage.createListingSyncTask(validatedData);
      return res.status(201).json(task);
    } catch (error: any) {
      console.error('Error creating listing task:', error);
      return res.status(500).json({ message: `Error creating listing task: ${error.message}` });
    }
  });

  app.post('/api/listing-tasks/:id/complete', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const taskId = parseInt(req.params.id);
      if (isNaN(taskId)) {
        return res.status(400).json({ message: 'Invalid task ID' });
      }
      
      // Get task to check ownership
      const task = await storage.getListingSyncTask(taskId);
      
      if (!task) {
        return res.status(404).json({ message: 'Task not found' });
      }
      
      if (task.userId !== req.user.id && !req.user.isAdmin) {
        return res.status(403).json({ message: 'Not authorized to complete this task' });
      }
      
      // Complete task
      const completedTask = await storage.markTaskCompleted(taskId);
      
      // If task was for a listing verification, update the listing as well
      if (task.listingId && task.taskType === 'Verification') {
        await storage.updateBusinessListing(task.listingId, {
          verificationStatus: true,
          syncStatus: 'synced'
        });
      }
      
      return res.json(completedTask);
    } catch (error: any) {
      console.error('Error completing task:', error);
      return res.status(500).json({ message: `Error completing task: ${error.message}` });
    }
  });

  // Business reviews endpoints
  app.get('/api/business-reviews', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const platform = req.query.platform as string;
      const reviews = await storage.getUserBusinessReviews(req.user.id, platform);
      return res.json(reviews);
    } catch (error: any) {
      console.error('Error fetching business reviews:', error);
      return res.status(500).json({ message: `Error fetching business reviews: ${error.message}` });
    }
  });

  app.post('/api/business-reviews/:id/respond', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const reviewId = parseInt(req.params.id);
      if (isNaN(reviewId)) {
        return res.status(400).json({ message: 'Invalid review ID' });
      }
      
      const { responseText } = req.body;
      if (!responseText) {
        return res.status(400).json({ message: 'Response text is required' });
      }
      
      // Get review to check ownership
      const review = await storage.getBusinessReview(reviewId);
      
      if (!review) {
        return res.status(404).json({ message: 'Review not found' });
      }
      
      if (review.userId !== req.user.id && !req.user.isAdmin) {
        return res.status(403).json({ message: 'Not authorized to respond to this review' });
      }
      
      // Add response
      const updatedReview = await storage.respondToReview(reviewId, responseText);
      return res.json(updatedReview);
    } catch (error: any) {
      console.error('Error responding to review:', error);
      return res.status(500).json({ message: `Error responding to review: ${error.message}` });
    }
  });

  // Listings analytics
  app.get('/api/analytics/listings', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      const stats = await storage.getListingsStats(req.user.id);
      return res.json(stats);
    } catch (error: any) {
      console.error('Error fetching listings stats:', error);
      return res.status(500).json({ message: `Error fetching listings stats: ${error.message}` });
    }
  });

  const httpServer = createServer(app);

  return httpServer;
}
