import type { Express, Request, Response, NextFunction } from "express";
import { createServer, type Server } from "http";
import Stripe from "stripe";
import { db } from "./db";
import { setupAuth } from "./auth";
import { contentPipelineService } from "./cds-integration";
import {
  connectFacebookAccount,
  getFacebookPages,
  disconnectFacebookIntegration,
  postToFacebook
} from './integrations/facebook';
import axios from 'axios';
import {
  users,
  contents,
  schedules,
  contentTypeEnum,
  contentStatusEnum,
  frequencyEnum,
  toneEnum,
  platformEnum,
  companyProfiles,
  autoContentConfigs,
  autoGeneratedContents,
  autoContentStatusEnum,
  contentPipelines,
  pipelineRunStatusEnum,
  contentPipelineRuns,
  platformIntegrations
} from "@shared/schema";
import { eq, and, desc, sql, SQL, asc } from "drizzle-orm";

// Initialize Stripe
if (!process.env.STRIPE_SECRET_KEY) {
  console.warn('Warning: STRIPE_SECRET_KEY environment variable not set. Stripe functionality will be limited.');
}

const stripe = process.env.STRIPE_SECRET_KEY 
  ? new Stripe(process.env.STRIPE_SECRET_KEY, { apiVersion: "2025-03-31.basil" })
  : null;

// Define subscription plan price IDs
const EMBER_PLAN_PRICE_ID = process.env.STRIPE_EMBER_PLAN_PRICE_ID;
const INFERNO_PLAN_PRICE_ID = process.env.STRIPE_INFERNO_PLAN_PRICE_ID;

export async function registerRoutes(app: Express): Promise<Server> {
  // Authentication routes
  setupAuth(app);

  // Facebook integration endpoints
  
  // Client-side SDK auth endpoint (used by the FacebookLoginButton component)
  app.post('/api/integrations/facebook/connect', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    const { accessToken, userID, name, email } = req.body;
    
    if (!accessToken || !userID) {
      return res.status(400).json({ message: 'Access token and user ID are required' });
    }
    
    try {
      // Verify the access token with Facebook
      const verifyResponse = await axios.get(`https://graph.facebook.com/debug_token`, {
        params: {
          input_token: accessToken,
          access_token: `${process.env.FACEBOOK_APP_ID}|${process.env.FACEBOOK_APP_SECRET}`,
        },
      });
      
      const tokenData = verifyResponse.data.data;
      
      // Verify the token is valid and for the correct user
      if (!tokenData.is_valid || tokenData.user_id !== userID) {
        throw new Error('Invalid Facebook access token');
      }
      
      // Connect the Facebook account using our helper
      const result = await connectFacebookAccount(req.user.id, {
        accessToken,
        userID,
        name,
        email
      });
      
      res.json(result);
    } catch (error) {
      console.error('Failed to connect Facebook account:', error);
      res.status(500).json({ 
        message: 'Failed to connect Facebook account: ' + (error instanceof Error ? error.message : 'Unknown error')
      });
    }
  });

  // Post to Facebook using our client component 
  app.post('/api/integrations/facebook/post', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }

    const { text, imageUrl, pageId, pageAccessToken } = req.body;

    if (!text && !imageUrl) {
      return res.status(400).json({ message: 'Either text or image is required' });
    }

    if (!pageId || !pageAccessToken) {
      return res.status(400).json({ message: 'Page ID and access token are required' });
    }

    try {
      const result = await postToFacebook({
        text,
        imageUrl,
        pageId,
        pageAccessToken
      });
      
      res.json(result);
    } catch (error) {
      console.error('Failed to post to Facebook:', error);
      res.status(500).json({ 
        message: 'Failed to post to Facebook: ' + (error instanceof Error ? error.message : 'Unknown error')
      });
    }
  });

  // Get Facebook pages
  app.get('/api/integrations/facebook/pages', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }

    try {
      const pages = await getFacebookPages(req.user.id);
      res.json(pages);
    } catch (error) {
      console.error('Failed to get Facebook pages:', error);
      res.status(500).json({ 
        message: 'Failed to get Facebook pages: ' + (error instanceof Error ? error.message : 'Unknown error')
      });
    }
  });

  // Disconnect Facebook integration
  app.delete('/api/integrations/facebook', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }

    try {
      const result = await disconnectFacebookIntegration(req.user.id);
      res.json(result);
    } catch (error) {
      console.error('Failed to disconnect Facebook account:', error);
      res.status(500).json({ 
        message: 'Failed to disconnect Facebook account: ' + (error instanceof Error ? error.message : 'Unknown error')
      });
    }
  });

  // Get all user's integrations
  app.get('/api/integrations', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }

    try {
      const integrations = await db.select()
        .from(platformIntegrations)
        .where(eq(platformIntegrations.userId, req.user.id));
      
      // Format for client
      const formattedIntegrations = integrations.map(integration => ({
        id: integration.id,
        platform: integration.platform,
        platformUsername: integration.accountName,
        platformImageUrl: integration.profileImageUrl,
        isConnected: integration.isActive,
        lastUsed: integration.lastUsed
      }));
      
      res.json(formattedIntegrations);
    } catch (error) {
      console.error('Failed to get integrations:', error);
      res.status(500).json({ 
        message: 'Failed to get integrations: ' + (error instanceof Error ? error.message : 'Unknown error')
      });
    }
  });

  // The rest of your routes here
  // ...

  const httpServer = createServer(app);
  return httpServer;
}