import type { Express, Request, Response, NextFunction } from "express";
import { createServer, type Server } from "http";
import Stripe from "stripe";
import { db } from "./db";
import { setupAuth } from "./auth";
import { contentPipelineService } from "./cds-integration";
import {
  connectFacebookAccount,
  getFacebookPages,
  disconnectFacebookIntegration,
  postToFacebook
} from './integrations/facebook';
import {
  getAuthorizationUrl,
  getAccessToken,
  getUserProfile,
  shareTextPost,
  shareImagePost,
  shareVideoPost,
  isAccessTokenValid
} from './integrations/linkedin';
import { getCompanyProfile, saveCompanyProfile } from './routes/company-profile';
import { getBrandSettings, saveBrandSettings } from './routes/brand-settings';
import { createAnimationHandler, listAnimationsHandler } from './routes/animations';
import axios from 'axios';
import {
  users,
  contents,
  schedules,
  contentTypeEnum,
  contentStatusEnum,
  frequencyEnum,
  toneEnum,
  platformEnum,
  companyProfiles,
  autoContentConfigs,
  autoGeneratedContents,
  autoContentStatusEnum,
  contentPipelines,
  pipelineRunStatusEnum,
  contentPipelineRuns,
  platformIntegrations
} from "@shared/schema";
import { eq, and, desc, sql, SQL, asc } from "drizzle-orm";

// Initialize Stripe
if (!process.env.STRIPE_SECRET_KEY) {
  console.warn('Warning: STRIPE_SECRET_KEY environment variable not set. Stripe functionality will be limited.');
}

const stripe = process.env.STRIPE_SECRET_KEY 
  ? new Stripe(process.env.STRIPE_SECRET_KEY, { apiVersion: "2025-03-31.basil" })
  : null;

// Define subscription plan price IDs
const EMBER_PLAN_PRICE_ID = process.env.STRIPE_EMBER_PLAN_PRICE_ID;
const INFERNO_PLAN_PRICE_ID = process.env.STRIPE_INFERNO_PLAN_PRICE_ID;

export async function registerRoutes(app: Express): Promise<Server> {
  // Authentication routes
  setupAuth(app);

  // Facebook integration endpoints
  
  // Client-side SDK auth endpoint (used by the FacebookLoginButton component)
  app.post('/api/integrations/facebook/connect', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    const { accessToken, userID, name, email } = req.body;
    
    if (!accessToken || !userID) {
      return res.status(400).json({ message: 'Access token and user ID are required' });
    }
    
    try {
      // Verify the access token with Facebook
      const verifyResponse = await axios.get(`https://graph.facebook.com/debug_token`, {
        params: {
          input_token: accessToken,
          access_token: `${process.env.FACEBOOK_APP_ID}|${process.env.FACEBOOK_APP_SECRET}`,
        },
      });
      
      const tokenData = verifyResponse.data.data;
      
      // Verify the token is valid and for the correct user
      if (!tokenData.is_valid || tokenData.user_id !== userID) {
        throw new Error('Invalid Facebook access token');
      }
      
      // Connect the Facebook account using our helper
      const result = await connectFacebookAccount(req.user.id, {
        accessToken,
        userID,
        name,
        email
      });
      
      res.json(result);
    } catch (error) {
      console.error('Failed to connect Facebook account:', error);
      res.status(500).json({ 
        message: 'Failed to connect Facebook account: ' + (error instanceof Error ? error.message : 'Unknown error')
      });
    }
  });

  // Post to Facebook using our client component 
  app.post('/api/integrations/facebook/post', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }

    const { text, imageUrl, pageId, pageAccessToken } = req.body;

    if (!text && !imageUrl) {
      return res.status(400).json({ message: 'Either text or image is required' });
    }

    if (!pageId || !pageAccessToken) {
      return res.status(400).json({ message: 'Page ID and access token are required' });
    }

    try {
      const result = await postToFacebook({
        text,
        imageUrl,
        pageId,
        pageAccessToken
      });
      
      res.json(result);
    } catch (error) {
      console.error('Failed to post to Facebook:', error);
      res.status(500).json({ 
        message: 'Failed to post to Facebook: ' + (error instanceof Error ? error.message : 'Unknown error')
      });
    }
  });

  // Get Facebook pages
  app.get('/api/integrations/facebook/pages', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }

    try {
      const pages = await getFacebookPages(req.user.id);
      res.json(pages);
    } catch (error) {
      console.error('Failed to get Facebook pages:', error);
      res.status(500).json({ 
        message: 'Failed to get Facebook pages: ' + (error instanceof Error ? error.message : 'Unknown error')
      });
    }
  });

  // Disconnect Facebook integration
  app.delete('/api/integrations/facebook', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }

    try {
      const result = await disconnectFacebookIntegration(req.user.id);
      res.json(result);
    } catch (error) {
      console.error('Failed to disconnect Facebook account:', error);
      res.status(500).json({ 
        message: 'Failed to disconnect Facebook account: ' + (error instanceof Error ? error.message : 'Unknown error')
      });
    }
  });

  // Get all user's integrations
  app.get('/api/integrations', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }

    try {
      const integrations = await db.select()
        .from(platformIntegrations)
        .where(eq(platformIntegrations.userId, req.user.id));
      
      // Format for client
      const formattedIntegrations = integrations.map(integration => ({
        id: integration.id,
        platform: integration.platform,
        platformUsername: integration.accountName,
        platformImageUrl: integration.profileImageUrl,
        isConnected: integration.isActive,
        lastUsed: integration.lastUsed
      }));
      
      res.json(formattedIntegrations);
    } catch (error) {
      console.error('Failed to get integrations:', error);
      res.status(500).json({ 
        message: 'Failed to get integrations: ' + (error instanceof Error ? error.message : 'Unknown error')
      });
    }
  });

  // Company Profile endpoints
  app.get('/api/company-profile', getCompanyProfile);
  app.post('/api/company-profile', saveCompanyProfile);
  
  // Brand Settings endpoints
  app.get('/api/brand-settings', getBrandSettings);
  app.post('/api/brand-settings', saveBrandSettings);
  
  // AnimateDiff endpoints
  app.post('/api/animations', createAnimationHandler);
  app.get('/api/animations', listAnimationsHandler);
  
  // LinkedIn Integration endpoints
  
  // Get LinkedIn authorization URL
  app.get('/api/integrations/linkedin/auth-url', (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      // The OAuth redirect URI that LinkedIn will redirect back to
      const redirectUri = `${req.protocol}://${req.get('host')}/api/integrations/linkedin/callback`;
      const authUrl = getLinkedInAuthUrl(redirectUri);
      res.json({ authUrl });
    } catch (error) {
      console.error('Failed to get LinkedIn auth URL:', error);
      res.status(500).json({ 
        message: 'Failed to get LinkedIn auth URL: ' + (error instanceof Error ? error.message : 'Unknown error')
      });
    }
  });
  
  // OAuth callback endpoint that LinkedIn will redirect to
  app.get('/api/integrations/linkedin/callback', async (req: Request, res: Response) => {
    const { code, state, error } = req.query;
    
    // Handle error from LinkedIn
    if (error) {
      return res.redirect(`/settings?error=${encodeURIComponent(error as string)}`);
    }
    
    // Validate state to prevent CSRF
    if (state !== 'linkedInAuth') {
      return res.redirect('/settings?error=invalid_state');
    }
    
    if (!code) {
      return res.redirect('/settings?error=missing_code');
    }
    
    try {
      // The redirectUri must be the same as the one used to get the auth URL
      const redirectUri = `${req.protocol}://${req.get('host')}/api/integrations/linkedin/callback`;
      
      // Exchange the code for an access token
      const tokenResponse = await getAccessTokenFromCode(code as string, redirectUri);
      
      // Get the user's LinkedIn profile
      const profile = await getLinkedInProfile(tokenResponse.access_token);
      
      // Store the integration in the database
      if (req.isAuthenticated()) {
        await saveLinkedInIntegration(
          req.user.id, 
          tokenResponse.access_token, 
          tokenResponse.expires_in,
          profile
        );
      }
      
      // Redirect back to the settings page
      return res.redirect('/settings?linkedin=connected');
    } catch (error) {
      console.error('LinkedIn OAuth callback error:', error);
      return res.redirect(`/settings?error=${encodeURIComponent(error instanceof Error ? error.message : 'Unknown error')}`);
    }
  });
  
  // Post to LinkedIn
  app.post('/api/integrations/linkedin/post', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    const { text, imageUrl, link, title, description } = req.body;
    
    if (!text && !imageUrl && !link) {
      return res.status(400).json({ message: 'At least one of text, image, or link is required' });
    }
    
    try {
      // Get the user's LinkedIn integration
      const [integration] = await db
        .select()
        .from(platformIntegrations)
        .where(
          eq(platformIntegrations.userId, req.user.id) && 
          eq(platformIntegrations.platform, 'linkedin')
        );
      
      if (!integration || !integration.isActive) {
        return res.status(400).json({ message: 'LinkedIn integration not found or inactive' });
      }
      
      // Verify token is still valid
      const isTokenValid = await validateAccessToken(integration.accessToken);
      
      if (!isTokenValid) {
        return res.status(401).json({ message: 'LinkedIn access token expired, please reconnect' });
      }
      
      // Post to LinkedIn
      const result = await axios.post(
        'https://api.linkedin.com/v2/ugcPosts',
        {
          author: `urn:li:person:${integration.accountId}`,
          lifecycleState: 'PUBLISHED',
          specificContent: {
            'com.linkedin.ugc.ShareContent': {
              shareCommentary: {
                text: text || ''
              },
              shareMediaCategory: link ? 'ARTICLE' : imageUrl ? 'IMAGE' : 'NONE',
              media: link || imageUrl ? [
                link ? {
                  status: 'READY',
                  originalUrl: link,
                  title: {
                    text: title || link
                  },
                  description: {
                    text: description || ''
                  }
                } : {
                  status: 'READY',
                  description: {
                    text: description || ''
                  },
                  media: `urn:li:image:${imageUrl}`,
                  title: {
                    text: title || ''
                  }
                }
              ] : undefined
            }
          },
          visibility: {
            'com.linkedin.ugc.MemberNetworkVisibility': 'PUBLIC'
          }
        },
        {
          headers: {
            Authorization: `Bearer ${integration.accessToken}`,
            'Content-Type': 'application/json',
            'X-Restli-Protocol-Version': '2.0.0'
          }
        }
      );
      
      // Update the last used timestamp
      await db
        .update(platformIntegrations)
        .set({
          lastUsed: new Date(),
          updatedAt: new Date()
        })
        .where(eq(platformIntegrations.id, integration.id));
      
      res.json(result.data);
    } catch (error) {
      console.error('Failed to post to LinkedIn:', error);
      res.status(500).json({ 
        message: 'Failed to post to LinkedIn: ' + (error instanceof Error ? error.message : 'Unknown error')
      });
    }
  });
  
  // Disconnect LinkedIn integration
  app.delete('/api/integrations/linkedin', async (req: Request, res: Response) => {
    if (!req.isAuthenticated()) {
      return res.status(401).json({ message: 'Not authenticated' });
    }
    
    try {
      // Find the integration
      const [integration] = await db
        .select()
        .from(platformIntegrations)
        .where(
          eq(platformIntegrations.userId, req.user.id) && 
          eq(platformIntegrations.platform, 'linkedin')
        );
      
      if (!integration) {
        return res.status(404).json({ message: 'LinkedIn integration not found' });
      }
      
      // Mark as inactive instead of deleting
      await db
        .update(platformIntegrations)
        .set({
          isActive: false,
          updatedAt: new Date()
        })
        .where(eq(platformIntegrations.id, integration.id));
      
      res.json({ success: true });
    } catch (error) {
      console.error('Failed to disconnect LinkedIn account:', error);
      res.status(500).json({ 
        message: 'Failed to disconnect LinkedIn account: ' + (error instanceof Error ? error.message : 'Unknown error')
      });
    }
  });

  const httpServer = createServer(app);
  return httpServer;
}