import { 
  users, 
  contents, 
  schedules, 
  socialAccounts, 
  adminSettings, 
  companyProfiles, 
  autoContentConfigs,
  autoGeneratedContents,
  businessHours,
  businessListings,
  listingSyncTasks,
  businessReviews,
  type User, 
  type InsertUser, 
  type Content, 
  type InsertContent, 
  type Schedule, 
  type InsertSchedule, 
  type SocialAccount, 
  type InsertSocialAccount, 
  type AdminSettings, 
  type InsertAdminSettings, 
  type CompanyProfile, 
  type InsertCompanyProfile,
  type AutoContentConfig,
  type InsertAutoContentConfig,
  type AutoGeneratedContent,
  type InsertAutoGeneratedContent,
  type BusinessHours,
  type InsertBusinessHours,
  type BusinessListing,
  type InsertBusinessListing,
  type ListingSyncTask,
  type InsertListingSyncTask,
  type BusinessReview,
  type InsertBusinessReview
} from "@shared/schema";
import { db, pool } from "./db";
import { eq, and, desc, gte, sql } from "drizzle-orm";
import session from "express-session";
import connectPg from "connect-pg-simple";

const PostgresSessionStore = connectPg(session);

// Interface for storage operations
export interface IStorage {
  // User operations
  getUser(id: number): Promise<User | undefined>;
  getUserByUsername(username: string): Promise<User | undefined>;
  getUserByEmail(email: string): Promise<User | undefined>;
  createUser(user: InsertUser): Promise<User>;
  updateUser(id: number, data: Partial<User>): Promise<User>;
  updateStripeInfo(id: number, stripeCustomerId: string, stripeSubscriptionId: string): Promise<User>;
  
  // Content operations
  createContent(content: InsertContent): Promise<Content>;
  getContent(id: number): Promise<Content | undefined>;
  getUserContents(userId: number, limit?: number): Promise<Content[]>;
  updateContent(id: number, data: Partial<Content>): Promise<Content>;
  deleteContent(id: number): Promise<boolean>;
  
  // Schedule operations
  createSchedule(schedule: InsertSchedule): Promise<Schedule>;
  getSchedule(id: number): Promise<Schedule | undefined>;
  getContentSchedules(contentId: number): Promise<Schedule[]>;
  getUpcomingSchedules(userId: number, limit?: number): Promise<(Schedule & { content: Content })[]>;
  markSchedulePublished(id: number, metrics?: string): Promise<Schedule>;
  deleteSchedule(id: number): Promise<boolean>;
  
  // Social account operations
  createSocialAccount(account: InsertSocialAccount): Promise<SocialAccount>;
  getUserSocialAccounts(userId: number): Promise<SocialAccount[]>;
  updateSocialAccount(id: number, data: Partial<SocialAccount>): Promise<SocialAccount>;
  deleteSocialAccount(id: number): Promise<boolean>;
  
  // Company profile operations
  getCompanyProfile(userId: number): Promise<CompanyProfile | undefined>;
  createCompanyProfile(profile: InsertCompanyProfile): Promise<CompanyProfile>;
  updateCompanyProfile(id: number, data: Partial<CompanyProfile>): Promise<CompanyProfile>;
  
  // Admin settings operations
  getAdminSettings(): Promise<AdminSettings | undefined>;
  createOrUpdateAdminSettings(settings: InsertAdminSettings): Promise<AdminSettings>;
  
  // Auto content operations
  getAutoContentConfig(userId: number): Promise<AutoContentConfig | undefined>;
  createAutoContentConfig(config: InsertAutoContentConfig): Promise<AutoContentConfig>;
  updateAutoContentConfig(userId: number, data: Partial<AutoContentConfig>): Promise<AutoContentConfig>;
  
  // Auto generated content operations
  createAutoGeneratedContent(content: InsertAutoGeneratedContent): Promise<AutoGeneratedContent>;
  getUpcomingAutoContent(userId: number): Promise<AutoGeneratedContent[]>;
  getAutoContentHistory(userId: number): Promise<AutoGeneratedContent[]>;
  cancelAutoContent(id: number): Promise<boolean>;
  markAutoContentPublished(id: number, metrics?: string): Promise<AutoGeneratedContent>;
  
  // Analytics
  getContentStats(userId: number): Promise<{ 
    totalContent: number, 
    publishedContent: number, 
    totalImages: number,
    totalEngagement: number
  }>;
  
  // Business Listings operations
  // Business Hours operations
  getBusinessHours(companyProfileId: number): Promise<BusinessHours | undefined>;
  createBusinessHours(hours: InsertBusinessHours): Promise<BusinessHours>;
  updateBusinessHours(id: number, data: Partial<BusinessHours>): Promise<BusinessHours>;
  
  // Business Listings operations
  createBusinessListing(listing: InsertBusinessListing): Promise<BusinessListing>;
  getBusinessListing(id: number): Promise<BusinessListing | undefined>;
  getBusinessListingByPlatform(userId: number, platform: string): Promise<BusinessListing | undefined>;
  getUserBusinessListings(userId: number): Promise<BusinessListing[]>;
  updateBusinessListing(id: number, data: Partial<BusinessListing>): Promise<BusinessListing>;
  deleteBusinessListing(id: number): Promise<boolean>;
  
  // Listing Sync Tasks operations
  createListingSyncTask(task: InsertListingSyncTask): Promise<ListingSyncTask>;
  getListingSyncTask(id: number): Promise<ListingSyncTask | undefined>;
  getUserListingSyncTasks(userId: number, status?: string): Promise<ListingSyncTask[]>;
  getListingTasks(listingId: number): Promise<ListingSyncTask[]>;
  updateListingSyncTask(id: number, data: Partial<ListingSyncTask>): Promise<ListingSyncTask>;
  markTaskCompleted(id: number): Promise<ListingSyncTask>;
  deleteListingSyncTask(id: number): Promise<boolean>;
  
  // Business Reviews operations
  createBusinessReview(review: InsertBusinessReview): Promise<BusinessReview>;
  getBusinessReview(id: number): Promise<BusinessReview | undefined>;
  getUserBusinessReviews(userId: number, platform?: string): Promise<BusinessReview[]>;
  getListingReviews(listingId: number): Promise<BusinessReview[]>;
  updateBusinessReview(id: number, data: Partial<BusinessReview>): Promise<BusinessReview>;
  respondToReview(id: number, responseText: string): Promise<BusinessReview>;
  deleteBusinessReview(id: number): Promise<boolean>;
  
  // Listings Analytics
  getListingsStats(userId: number): Promise<{
    totalListings: number,
    verifiedListings: number,
    pendingListings: number,
    totalReviews: number,
    averageRating: number
  }>;
  
  // Session store
  sessionStore: any; // Using any type for SessionStore to avoid TypeScript issues
}

// Database storage implementation
export class DatabaseStorage implements IStorage {
  sessionStore: any; // Using any type for SessionStore to avoid TypeScript issues
  
  constructor() {
    this.sessionStore = new PostgresSessionStore({ 
      pool, 
      tableName: 'session',
      createTableIfMissing: true 
    });
  }
  
  // User operations
  async getUser(id: number): Promise<User | undefined> {
    const [user] = await db.select().from(users).where(eq(users.id, id));
    return user;
  }
  
  async getUserByUsername(username: string): Promise<User | undefined> {
    const [user] = await db.select().from(users).where(eq(users.username, username));
    return user;
  }
  
  async getUserByEmail(email: string): Promise<User | undefined> {
    const [user] = await db.select().from(users).where(eq(users.email, email));
    return user;
  }
  
  async createUser(user: InsertUser): Promise<User> {
    const [createdUser] = await db.insert(users).values(user).returning();
    return createdUser;
  }
  
  async updateUser(id: number, data: Partial<User>): Promise<User> {
    const [updatedUser] = await db
      .update(users)
      .set(data)
      .where(eq(users.id, id))
      .returning();
    return updatedUser;
  }
  
  async updateStripeInfo(id: number, stripeCustomerId: string, stripeSubscriptionId: string): Promise<User> {
    const [updatedUser] = await db
      .update(users)
      .set({ 
        stripeCustomerId,
        stripeSubscriptionId
      })
      .where(eq(users.id, id))
      .returning();
    return updatedUser;
  }
  
  // Content operations
  async createContent(content: InsertContent): Promise<Content> {
    const [createdContent] = await db.insert(contents).values(content).returning();
    return createdContent;
  }
  
  async getContent(id: number): Promise<Content | undefined> {
    const [content] = await db.select().from(contents).where(eq(contents.id, id));
    return content;
  }
  
  async getUserContents(userId: number, limit?: number): Promise<Content[]> {
    let query = db.select()
      .from(contents)
      .where(eq(contents.userId, userId))
      .orderBy(desc(contents.createdAt));
    
    if (limit) {
      query = query.limit(limit);
    }
    
    return await query;
  }
  
  async updateContent(id: number, data: Partial<Content>): Promise<Content> {
    const [updatedContent] = await db
      .update(contents)
      .set({
        ...data,
        updatedAt: new Date()
      })
      .where(eq(contents.id, id))
      .returning();
    return updatedContent;
  }
  
  async deleteContent(id: number): Promise<boolean> {
    const result = await db.delete(contents).where(eq(contents.id, id));
    return true;
  }
  
  // Schedule operations
  async createSchedule(schedule: InsertSchedule): Promise<Schedule> {
    const [createdSchedule] = await db.insert(schedules).values(schedule).returning();
    return createdSchedule;
  }
  
  async getSchedule(id: number): Promise<Schedule | undefined> {
    const [schedule] = await db.select().from(schedules).where(eq(schedules.id, id));
    return schedule;
  }
  
  async getContentSchedules(contentId: number): Promise<Schedule[]> {
    return await db.select()
      .from(schedules)
      .where(eq(schedules.contentId, contentId));
  }
  
  async getUpcomingSchedules(userId: number, limit?: number): Promise<(Schedule & { content: Content })[]> {
    const now = new Date();
    
    let query = db.select({
      schedule: schedules,
      content: contents
    })
    .from(schedules)
    .innerJoin(contents, eq(schedules.contentId, contents.id))
    .where(
      and(
        eq(contents.userId, userId),
        gte(schedules.scheduledDate, now),
        eq(schedules.published, false)
      )
    )
    .orderBy(schedules.scheduledDate);
    
    if (limit) {
      query = query.limit(limit);
    }
    
    const results = await query;
    return results.map(r => ({ ...r.schedule, content: r.content }));
  }
  
  async markSchedulePublished(id: number, metrics?: string): Promise<Schedule> {
    const [updatedSchedule] = await db
      .update(schedules)
      .set({
        published: true,
        publishedDate: new Date(),
        engagementMetrics: metrics || null
      })
      .where(eq(schedules.id, id))
      .returning();
    return updatedSchedule;
  }
  
  async deleteSchedule(id: number): Promise<boolean> {
    await db.delete(schedules).where(eq(schedules.id, id));
    return true;
  }
  
  // Social account operations
  async createSocialAccount(account: InsertSocialAccount): Promise<SocialAccount> {
    const [createdAccount] = await db.insert(socialAccounts).values(account).returning();
    return createdAccount;
  }
  
  async getUserSocialAccounts(userId: number): Promise<SocialAccount[]> {
    return await db.select()
      .from(socialAccounts)
      .where(eq(socialAccounts.userId, userId));
  }
  
  async updateSocialAccount(id: number, data: Partial<SocialAccount>): Promise<SocialAccount> {
    const [updatedAccount] = await db
      .update(socialAccounts)
      .set(data)
      .where(eq(socialAccounts.id, id))
      .returning();
    return updatedAccount;
  }
  
  async deleteSocialAccount(id: number): Promise<boolean> {
    await db.delete(socialAccounts).where(eq(socialAccounts.id, id));
    return true;
  }
  
  // Company profile operations
  async getCompanyProfile(userId: number): Promise<CompanyProfile | undefined> {
    const [profile] = await db
      .select()
      .from(companyProfiles)
      .where(eq(companyProfiles.userId, userId));
    return profile;
  }
  
  async createCompanyProfile(profile: InsertCompanyProfile): Promise<CompanyProfile> {
    const [createdProfile] = await db
      .insert(companyProfiles)
      .values(profile)
      .returning();
    return createdProfile;
  }
  
  async updateCompanyProfile(id: number, data: Partial<CompanyProfile>): Promise<CompanyProfile> {
    const [updatedProfile] = await db
      .update(companyProfiles)
      .set({
        ...data,
        updatedAt: new Date()
      })
      .where(eq(companyProfiles.id, id))
      .returning();
    return updatedProfile;
  }
  
  // Admin settings operations
  async getAdminSettings(): Promise<AdminSettings | undefined> {
    const [settings] = await db.select().from(adminSettings);
    return settings;
  }
  
  async createOrUpdateAdminSettings(settings: InsertAdminSettings): Promise<AdminSettings> {
    // Check if settings exist
    const existingSettings = await this.getAdminSettings();
    
    if (existingSettings) {
      // Update
      const [updatedSettings] = await db
        .update(adminSettings)
        .set(settings)
        .where(eq(adminSettings.id, existingSettings.id))
        .returning();
      return updatedSettings;
    } else {
      // Create
      const [createdSettings] = await db
        .insert(adminSettings)
        .values(settings)
        .returning();
      return createdSettings;
    }
  }
  
  // Auto content operations
  async getAutoContentConfig(userId: number): Promise<AutoContentConfig | undefined> {
    const [config] = await db.select()
      .from(autoContentConfigs)
      .where(eq(autoContentConfigs.userId, userId));
    
    return config;
  }
  
  async createAutoContentConfig(config: InsertAutoContentConfig): Promise<AutoContentConfig> {
    const [createdConfig] = await db.insert(autoContentConfigs)
      .values(config)
      .returning();
    
    return createdConfig;
  }
  
  async updateAutoContentConfig(userId: number, data: Partial<AutoContentConfig>): Promise<AutoContentConfig> {
    const [updatedConfig] = await db.update(autoContentConfigs)
      .set({
        ...data,
        updatedAt: new Date()
      })
      .where(eq(autoContentConfigs.userId, userId))
      .returning();
    
    return updatedConfig;
  }
  
  // Auto generated content operations
  async createAutoGeneratedContent(content: InsertAutoGeneratedContent): Promise<AutoGeneratedContent> {
    const [createdContent] = await db.insert(autoGeneratedContents)
      .values(content)
      .returning();
    
    return createdContent;
  }
  
  async getUpcomingAutoContent(userId: number): Promise<AutoGeneratedContent[]> {
    const now = new Date();
    
    // Using the and() operator for multiple conditions
    const result = await db.select()
      .from(autoGeneratedContents)
      .where(
        and(
          eq(autoGeneratedContents.userId, userId),
          eq(autoGeneratedContents.status, 'pending'),
          gte(autoGeneratedContents.scheduledDate, now)
        )
      )
      .orderBy(autoGeneratedContents.scheduledDate);
    
    return result;
  }
  
  async getAutoContentHistory(userId: number): Promise<AutoGeneratedContent[]> {
    // Using raw SQL for the status IN condition
    const result = await db.select()
      .from(autoGeneratedContents)
      .where(
        and(
          eq(autoGeneratedContents.userId, userId),
          sql`${autoGeneratedContents.status} IN ('published', 'failed')`
        )
      )
      .orderBy(desc(autoGeneratedContents.createdAt));
    
    return result;
  }
  
  async cancelAutoContent(id: number): Promise<boolean> {
    await db.delete(autoGeneratedContents)
      .where(eq(autoGeneratedContents.id, id));
    
    return true;
  }
  
  async markAutoContentPublished(id: number, metrics?: string): Promise<AutoGeneratedContent> {
    const [updatedContent] = await db.update(autoGeneratedContents)
      .set({
        status: 'published',
        publishedDate: new Date(),
        engagementMetrics: metrics || null
      })
      .where(eq(autoGeneratedContents.id, id))
      .returning();
    
    return updatedContent;
  }

  // Analytics
  async getContentStats(userId: number): Promise<{ 
    totalContent: number, 
    publishedContent: number, 
    totalImages: number,
    totalEngagement: number
  }> {
    // Total content count
    const [totalContentResult] = await db
      .select({ count: sql<number>`count(*)` })
      .from(contents)
      .where(eq(contents.userId, userId));
      
    // Published content count (via schedules)
    const [publishedContentResult] = await db
      .select({ count: sql<number>`count(distinct ${contents.id})` })
      .from(contents)
      .innerJoin(schedules, eq(contents.id, schedules.contentId))
      .where(
        and(
          eq(contents.userId, userId),
          eq(schedules.published, true)
        )
      );
      
    // Images count
    const [imagesResult] = await db
      .select({ count: sql<number>`count(*)` })
      .from(contents)
      .where(
        and(
          eq(contents.userId, userId),
          sql`${contents.imageUrl} is not null`
        )
      );
      
    // Get total engagement (sum of all engagement metrics that are numbers)
    const [engagementResult] = await db
      .select({
        totalEngagement: sql<number>`coalesce(sum((${schedules.engagementMetrics}::jsonb->>'total')::int), 0)`
      })
      .from(schedules)
      .innerJoin(contents, eq(schedules.contentId, contents.id))
      .where(
        and(
          eq(contents.userId, userId),
          eq(schedules.published, true),
          sql`${schedules.engagementMetrics} is not null`
        )
      );
      
    return {
      totalContent: totalContentResult.count || 0,
      publishedContent: publishedContentResult.count || 0,
      totalImages: imagesResult.count || 0,
      totalEngagement: engagementResult.totalEngagement || 0
    };
  }
  
  // Business Hours operations
  async getBusinessHours(companyProfileId: number): Promise<BusinessHours | undefined> {
    const [hours] = await db.select()
      .from(businessHours)
      .where(eq(businessHours.companyProfileId, companyProfileId));
    
    return hours;
  }
  
  async createBusinessHours(hours: InsertBusinessHours): Promise<BusinessHours> {
    const [createdHours] = await db.insert(businessHours)
      .values(hours)
      .returning();
    
    return createdHours;
  }
  
  async updateBusinessHours(id: number, data: Partial<BusinessHours>): Promise<BusinessHours> {
    const [updatedHours] = await db.update(businessHours)
      .set({
        ...data,
        updatedAt: new Date()
      })
      .where(eq(businessHours.id, id))
      .returning();
    
    return updatedHours;
  }
  
  // Business Listings operations
  async createBusinessListing(listing: InsertBusinessListing): Promise<BusinessListing> {
    const [createdListing] = await db.insert(businessListings)
      .values(listing)
      .returning();
    
    return createdListing;
  }
  
  async getBusinessListing(id: number): Promise<BusinessListing | undefined> {
    const [listing] = await db.select()
      .from(businessListings)
      .where(eq(businessListings.id, id));
    
    return listing;
  }
  
  async getBusinessListingByPlatform(userId: number, platform: string): Promise<BusinessListing | undefined> {
    const [listing] = await db.select()
      .from(businessListings)
      .where(
        and(
          eq(businessListings.userId, userId),
          eq(businessListings.platform, platform)
        )
      );
    
    return listing;
  }
  
  async getUserBusinessListings(userId: number): Promise<BusinessListing[]> {
    return await db.select()
      .from(businessListings)
      .where(eq(businessListings.userId, userId))
      .orderBy(businessListings.platform);
  }
  
  async updateBusinessListing(id: number, data: Partial<BusinessListing>): Promise<BusinessListing> {
    const [updatedListing] = await db.update(businessListings)
      .set({
        ...data,
        updatedAt: new Date()
      })
      .where(eq(businessListings.id, id))
      .returning();
    
    return updatedListing;
  }
  
  async deleteBusinessListing(id: number): Promise<boolean> {
    await db.delete(businessListings)
      .where(eq(businessListings.id, id));
    
    return true;
  }
  
  // Listing Sync Tasks operations
  async createListingSyncTask(task: InsertListingSyncTask): Promise<ListingSyncTask> {
    const [createdTask] = await db.insert(listingSyncTasks)
      .values(task)
      .returning();
    
    return createdTask;
  }
  
  async getListingSyncTask(id: number): Promise<ListingSyncTask | undefined> {
    const [task] = await db.select()
      .from(listingSyncTasks)
      .where(eq(listingSyncTasks.id, id));
    
    return task;
  }
  
  async getUserListingSyncTasks(userId: number, status?: string): Promise<ListingSyncTask[]> {
    let query = db.select()
      .from(listingSyncTasks)
      .where(eq(listingSyncTasks.userId, userId));
    
    if (status) {
      query = query.where(eq(listingSyncTasks.status, status));
    }
    
    return await query.orderBy(listingSyncTasks.dueDate);
  }
  
  async getListingTasks(listingId: number): Promise<ListingSyncTask[]> {
    return await db.select()
      .from(listingSyncTasks)
      .where(eq(listingSyncTasks.listingId, listingId))
      .orderBy(listingSyncTasks.dueDate);
  }
  
  async updateListingSyncTask(id: number, data: Partial<ListingSyncTask>): Promise<ListingSyncTask> {
    const [updatedTask] = await db.update(listingSyncTasks)
      .set({
        ...data,
        updatedAt: new Date()
      })
      .where(eq(listingSyncTasks.id, id))
      .returning();
    
    return updatedTask;
  }
  
  async markTaskCompleted(id: number): Promise<ListingSyncTask> {
    const [completedTask] = await db.update(listingSyncTasks)
      .set({
        status: 'completed',
        completedAt: new Date(),
        updatedAt: new Date()
      })
      .where(eq(listingSyncTasks.id, id))
      .returning();
    
    return completedTask;
  }
  
  async deleteListingSyncTask(id: number): Promise<boolean> {
    await db.delete(listingSyncTasks)
      .where(eq(listingSyncTasks.id, id));
    
    return true;
  }
  
  // Business Reviews operations
  async createBusinessReview(review: InsertBusinessReview): Promise<BusinessReview> {
    const [createdReview] = await db.insert(businessReviews)
      .values(review)
      .returning();
    
    return createdReview;
  }
  
  async getBusinessReview(id: number): Promise<BusinessReview | undefined> {
    const [review] = await db.select()
      .from(businessReviews)
      .where(eq(businessReviews.id, id));
    
    return review;
  }
  
  async getUserBusinessReviews(userId: number, platform?: string): Promise<BusinessReview[]> {
    let query = db.select()
      .from(businessReviews)
      .where(eq(businessReviews.userId, userId));
    
    if (platform) {
      query = query.where(eq(businessReviews.platform, platform));
    }
    
    return await query.orderBy(desc(businessReviews.reviewDate));
  }
  
  async getListingReviews(listingId: number): Promise<BusinessReview[]> {
    return await db.select()
      .from(businessReviews)
      .where(eq(businessReviews.listingId, listingId))
      .orderBy(desc(businessReviews.reviewDate));
  }
  
  async updateBusinessReview(id: number, data: Partial<BusinessReview>): Promise<BusinessReview> {
    const [updatedReview] = await db.update(businessReviews)
      .set({
        ...data,
        updatedAt: new Date()
      })
      .where(eq(businessReviews.id, id))
      .returning();
    
    return updatedReview;
  }
  
  async respondToReview(id: number, responseText: string): Promise<BusinessReview> {
    const [respondedReview] = await db.update(businessReviews)
      .set({
        responseText,
        responseDate: new Date(),
        updatedAt: new Date()
      })
      .where(eq(businessReviews.id, id))
      .returning();
    
    return respondedReview;
  }
  
  async deleteBusinessReview(id: number): Promise<boolean> {
    await db.delete(businessReviews)
      .where(eq(businessReviews.id, id));
    
    return true;
  }
  
  // Listings Analytics
  async getListingsStats(userId: number): Promise<{
    totalListings: number,
    verifiedListings: number,
    pendingListings: number,
    totalReviews: number,
    averageRating: number
  }> {
    // Total listings count
    const [totalListingsResult] = await db
      .select({ count: sql<number>`count(*)` })
      .from(businessListings)
      .where(eq(businessListings.userId, userId));
    
    // Verified listings count
    const [verifiedListingsResult] = await db
      .select({ count: sql<number>`count(*)` })
      .from(businessListings)
      .where(
        and(
          eq(businessListings.userId, userId),
          eq(businessListings.verificationStatus, true)
        )
      );
    
    // Pending listings (not synced yet)
    const [pendingListingsResult] = await db
      .select({ count: sql<number>`count(*)` })
      .from(businessListings)
      .where(
        and(
          eq(businessListings.userId, userId),
          eq(businessListings.syncStatus, 'pending')
        )
      );
    
    // Total reviews count
    const [totalReviewsResult] = await db
      .select({ count: sql<number>`count(*)` })
      .from(businessReviews)
      .where(eq(businessReviews.userId, userId));
    
    // Average rating
    const [averageRatingResult] = await db
      .select({
        avgRating: sql<number>`coalesce(avg(${businessReviews.rating}), 0)`
      })
      .from(businessReviews)
      .where(eq(businessReviews.userId, userId));
    
    return {
      totalListings: totalListingsResult.count || 0,
      verifiedListings: verifiedListingsResult.count || 0,
      pendingListings: pendingListingsResult.count || 0,
      totalReviews: totalReviewsResult.count || 0,
      averageRating: parseFloat(averageRatingResult.avgRating.toFixed(1)) || 0
    };
  }
}

export const storage = new DatabaseStorage();
